version: 1
project:
  name: ciwi
  vault:
    connection: home-vault
    secrets:
      - name: github-secret
        mount: kv
        path: gh
        key: token
        kv_version: 2

pipelines:
  - id: build
    trigger: manual
    source:
      repo: https://github.com/izzyreal/ciwi.git
    versioning:
      file: VERSION
      tag_prefix: v
    jobs:
      - id: unit-tests
        runs_on:
          executor: script
          shell: posix
        requires:
          tools:
            git: "*"
            go: ">=1.24"
        timeout_seconds: 600
        steps:
          - test:
              name: go-unit
              command: mkdir -p dist && go test -json -coverprofile=dist/go-unit.cover ./... > dist/go-unit.json
              format: go-test-json
              report: dist/go-unit.json
              coverage_format: go-coverprofile
              coverage_report: dist/go-unit.cover
      - id: build-cross-platform
        runs_on:
          executor: script
          shell: posix
        requires:
          tools:
            git: "*"
            go: ">=1.24"
        timeout_seconds: 600
        artifacts:
          - dist/**
        matrix:
          include:
            - name: linux-amd64
              goos: linux
              goarch: amd64
              ext: ""
            - name: windows-amd64
              goos: windows
              goarch: amd64
              ext: ".exe"
            - name: darwin-amd64
              goos: darwin
              goarch: amd64
              ext: ""
            - name: darwin-arm64
              goos: darwin
              goarch: arm64
              ext: ""
        steps:
          - run: mkdir -p dist
          - run: GOOS={{goos}} GOARCH={{goarch}} CGO_ENABLED=0 go build -v -trimpath -ldflags="-s -w -X github.com/izzyreal/ciwi/internal/version.Version=${CIWI_PIPELINE_VERSION}" -o dist/ciwi-{{name}}{{ext}} ./cmd/ciwi
  - id: release
    trigger: manual
    depends_on:
      - build
    source:
      repo: https://github.com/izzyreal/ciwi.git
    versioning:
      file: VERSION
      tag_prefix: v
      auto_bump: patch
    jobs:
      - id: github-release
        runs_on:
          executor: script
          shell: posix
        requires:
          tools:
            git: "*"
            gh: "*"
        timeout_seconds: 1200
        steps:
          - run: test -n "$GITHUB_TOKEN"
            skip_dry_run: true
            env:
              GITHUB_TOKEN: "{{ secret.github-secret }}"
          - run: git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/izzyreal/ciwi.git"
            skip_dry_run: true
            env:
              GITHUB_TOKEN: "{{ secret.github-secret }}"
          - run: test -f VERSION
          - run: |
              DIRTY="$(git status --porcelain | grep -vE '^\?\? dist/' || true)"
              if [ -n "$DIRTY" ]; then
                echo "working tree is not clean"
                exit 1
              fi
          - run: |
              TAG="${CIWI_PIPELINE_TAG}"
              if git rev-parse "$TAG" >/dev/null 2>&1; then
                echo "tag exists: $TAG"
                exit 1
              fi
              if git ls-remote --exit-code --tags origin "refs/tags/$TAG" >/dev/null 2>&1; then
                echo "remote tag exists: $TAG"
                exit 1
              fi
          - run: |
              test -f dist/ciwi-linux-amd64
              test -f dist/ciwi-darwin-amd64
              test -f dist/ciwi-darwin-arm64
              test -f dist/ciwi-windows-amd64.exe
              for f in \
                dist/ciwi-linux-amd64 \
                dist/ciwi-darwin-amd64 \
                dist/ciwi-darwin-arm64 \
                dist/ciwi-windows-amd64.exe; do
                shasum -a 256 "$f" | awk '{ sub(/^.*\//, "", $2); print $1 "  " $2 }'
              done > dist/ciwi-checksums.txt
              test -f dist/ciwi-checksums.txt
          - run: |
              TAG="${CIWI_PIPELINE_TAG}"
              git config user.name "ciwi-agent"
              git config user.email "ciwi-agent@local"
          - run: |
              TAG="${CIWI_PIPELINE_TAG}"
              git tag -a "$TAG" -m "ciwi $TAG"
              git push origin "$TAG"
            skip_dry_run: true
          - run: |
              TAG="${CIWI_PIPELINE_TAG}"
              gh release create "$TAG" \
                --repo izzyreal/ciwi \
                --title "ciwi $TAG" \
                --notes "Release $TAG"

              set -- \
                dist/ciwi-linux-amd64 \
                dist/ciwi-darwin-amd64 \
                dist/ciwi-darwin-arm64 \
                dist/ciwi-windows-amd64.exe \
                dist/ciwi-checksums.txt
              TOTAL="$#"
              IDX=0
              for FILE in "$@"; do
                IDX=$((IDX + 1))
                SIZE="$(wc -c < "$FILE" | tr -d ' ')"
                START="$(date +%s)"
                echo "[release] Uploading ${IDX}/${TOTAL}: ${FILE} (${SIZE} bytes)"
                gh release upload "$TAG" "$FILE" --repo izzyreal/ciwi --clobber
                END="$(date +%s)"
                echo "[release] Uploaded ${IDX}/${TOTAL}: ${FILE} in $((END-START))s"
              done
            skip_dry_run: true

pipeline_chains:
  - id: build-release
    pipelines:
      - build
      - release
