// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/ciwi/v1/ciwi.proto

package grpcapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetServerInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ApiVersion    int32                  `protobuf:"varint,2,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerInfoResponse) Reset() {
	*x = GetServerInfoResponse{}
	mi := &file_api_ciwi_v1_ciwi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerInfoResponse) ProtoMessage() {}

func (x *GetServerInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ciwi_v1_ciwi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerInfoResponse.ProtoReflect.Descriptor instead.
func (*GetServerInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_ciwi_v1_ciwi_proto_rawDescGZIP(), []int{0}
}

func (x *GetServerInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetServerInfoResponse) GetApiVersion() int32 {
	if x != nil {
		return x.ApiVersion
	}
	return 0
}

func (x *GetServerInfoResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *GetServerInfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ProjectSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ConfigPath    string                 `protobuf:"bytes,3,opt,name=config_path,json=configPath,proto3" json:"config_path,omitempty"`
	RepoUrl       string                 `protobuf:"bytes,4,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"`
	RepoRef       string                 `protobuf:"bytes,5,opt,name=repo_ref,json=repoRef,proto3" json:"repo_ref,omitempty"`
	ConfigFile    string                 `protobuf:"bytes,6,opt,name=config_file,json=configFile,proto3" json:"config_file,omitempty"`
	Pipelines     []*PipelineSummary     `protobuf:"bytes,7,rep,name=pipelines,proto3" json:"pipelines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectSummary) Reset() {
	*x = ProjectSummary{}
	mi := &file_api_ciwi_v1_ciwi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectSummary) ProtoMessage() {}

func (x *ProjectSummary) ProtoReflect() protoreflect.Message {
	mi := &file_api_ciwi_v1_ciwi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectSummary.ProtoReflect.Descriptor instead.
func (*ProjectSummary) Descriptor() ([]byte, []int) {
	return file_api_ciwi_v1_ciwi_proto_rawDescGZIP(), []int{1}
}

func (x *ProjectSummary) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProjectSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProjectSummary) GetConfigPath() string {
	if x != nil {
		return x.ConfigPath
	}
	return ""
}

func (x *ProjectSummary) GetRepoUrl() string {
	if x != nil {
		return x.RepoUrl
	}
	return ""
}

func (x *ProjectSummary) GetRepoRef() string {
	if x != nil {
		return x.RepoRef
	}
	return ""
}

func (x *ProjectSummary) GetConfigFile() string {
	if x != nil {
		return x.ConfigFile
	}
	return ""
}

func (x *ProjectSummary) GetPipelines() []*PipelineSummary {
	if x != nil {
		return x.Pipelines
	}
	return nil
}

type PipelineSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PipelineId    string                 `protobuf:"bytes,2,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	Trigger       string                 `protobuf:"bytes,3,opt,name=trigger,proto3" json:"trigger,omitempty"`
	DependsOn     []string               `protobuf:"bytes,4,rep,name=depends_on,json=dependsOn,proto3" json:"depends_on,omitempty"`
	SourceRepo    string                 `protobuf:"bytes,5,opt,name=source_repo,json=sourceRepo,proto3" json:"source_repo,omitempty"`
	SourceRef     string                 `protobuf:"bytes,6,opt,name=source_ref,json=sourceRef,proto3" json:"source_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipelineSummary) Reset() {
	*x = PipelineSummary{}
	mi := &file_api_ciwi_v1_ciwi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineSummary) ProtoMessage() {}

func (x *PipelineSummary) ProtoReflect() protoreflect.Message {
	mi := &file_api_ciwi_v1_ciwi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineSummary.ProtoReflect.Descriptor instead.
func (*PipelineSummary) Descriptor() ([]byte, []int) {
	return file_api_ciwi_v1_ciwi_proto_rawDescGZIP(), []int{2}
}

func (x *PipelineSummary) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PipelineSummary) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *PipelineSummary) GetTrigger() string {
	if x != nil {
		return x.Trigger
	}
	return ""
}

func (x *PipelineSummary) GetDependsOn() []string {
	if x != nil {
		return x.DependsOn
	}
	return nil
}

func (x *PipelineSummary) GetSourceRepo() string {
	if x != nil {
		return x.SourceRepo
	}
	return ""
}

func (x *PipelineSummary) GetSourceRef() string {
	if x != nil {
		return x.SourceRef
	}
	return ""
}

type ListProjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []*ProjectSummary      `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsResponse) Reset() {
	*x = ListProjectsResponse{}
	mi := &file_api_ciwi_v1_ciwi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsResponse) ProtoMessage() {}

func (x *ListProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ciwi_v1_ciwi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsResponse.ProtoReflect.Descriptor instead.
func (*ListProjectsResponse) Descriptor() ([]byte, []int) {
	return file_api_ciwi_v1_ciwi_proto_rawDescGZIP(), []int{3}
}

func (x *ListProjectsResponse) GetProjects() []*ProjectSummary {
	if x != nil {
		return x.Projects
	}
	return nil
}

type AgentInfo struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	AgentId              string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Hostname             string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os                   string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	Arch                 string                 `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`
	Version              string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	Capabilities         map[string]string      `protobuf:"bytes,6,rep,name=capabilities,proto3" json:"capabilities,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	LastSeenUtc          string                 `protobuf:"bytes,7,opt,name=last_seen_utc,json=lastSeenUtc,proto3" json:"last_seen_utc,omitempty"`
	RecentLog            []string               `protobuf:"bytes,8,rep,name=recent_log,json=recentLog,proto3" json:"recent_log,omitempty"`
	NeedsUpdate          bool                   `protobuf:"varint,9,opt,name=needs_update,json=needsUpdate,proto3" json:"needs_update,omitempty"`
	UpdateTarget         string                 `protobuf:"bytes,10,opt,name=update_target,json=updateTarget,proto3" json:"update_target,omitempty"`
	UpdateRequested      bool                   `protobuf:"varint,11,opt,name=update_requested,json=updateRequested,proto3" json:"update_requested,omitempty"`
	UpdateAttempts       int32                  `protobuf:"varint,12,opt,name=update_attempts,json=updateAttempts,proto3" json:"update_attempts,omitempty"`
	UpdateLastRequestUtc string                 `protobuf:"bytes,13,opt,name=update_last_request_utc,json=updateLastRequestUtc,proto3" json:"update_last_request_utc,omitempty"`
	UpdateNextRetryUtc   string                 `protobuf:"bytes,14,opt,name=update_next_retry_utc,json=updateNextRetryUtc,proto3" json:"update_next_retry_utc,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	mi := &file_api_ciwi_v1_ciwi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_ciwi_v1_ciwi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_api_ciwi_v1_ciwi_proto_rawDescGZIP(), []int{4}
}

func (x *AgentInfo) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AgentInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *AgentInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *AgentInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AgentInfo) GetCapabilities() map[string]string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *AgentInfo) GetLastSeenUtc() string {
	if x != nil {
		return x.LastSeenUtc
	}
	return ""
}

func (x *AgentInfo) GetRecentLog() []string {
	if x != nil {
		return x.RecentLog
	}
	return nil
}

func (x *AgentInfo) GetNeedsUpdate() bool {
	if x != nil {
		return x.NeedsUpdate
	}
	return false
}

func (x *AgentInfo) GetUpdateTarget() string {
	if x != nil {
		return x.UpdateTarget
	}
	return ""
}

func (x *AgentInfo) GetUpdateRequested() bool {
	if x != nil {
		return x.UpdateRequested
	}
	return false
}

func (x *AgentInfo) GetUpdateAttempts() int32 {
	if x != nil {
		return x.UpdateAttempts
	}
	return 0
}

func (x *AgentInfo) GetUpdateLastRequestUtc() string {
	if x != nil {
		return x.UpdateLastRequestUtc
	}
	return ""
}

func (x *AgentInfo) GetUpdateNextRetryUtc() string {
	if x != nil {
		return x.UpdateNextRetryUtc
	}
	return ""
}

type ListAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*AgentInfo           `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_api_ciwi_v1_ciwi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ciwi_v1_ciwi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_api_ciwi_v1_ciwi_proto_rawDescGZIP(), []int{5}
}

func (x *ListAgentsResponse) GetAgents() []*AgentInfo {
	if x != nil {
		return x.Agents
	}
	return nil
}

type GetAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentRequest) Reset() {
	*x = GetAgentRequest{}
	mi := &file_api_ciwi_v1_ciwi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentRequest) ProtoMessage() {}

func (x *GetAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ciwi_v1_ciwi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentRequest.ProtoReflect.Descriptor instead.
func (*GetAgentRequest) Descriptor() ([]byte, []int) {
	return file_api_ciwi_v1_ciwi_proto_rawDescGZIP(), []int{6}
}

func (x *GetAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type GetAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *AgentInfo             `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentResponse) Reset() {
	*x = GetAgentResponse{}
	mi := &file_api_ciwi_v1_ciwi_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentResponse) ProtoMessage() {}

func (x *GetAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ciwi_v1_ciwi_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentResponse.ProtoReflect.Descriptor instead.
func (*GetAgentResponse) Descriptor() ([]byte, []int) {
	return file_api_ciwi_v1_ciwi_proto_rawDescGZIP(), []int{7}
}

func (x *GetAgentResponse) GetAgent() *AgentInfo {
	if x != nil {
		return x.Agent
	}
	return nil
}

type JobDisplayGroupSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	JobCount      int32                  `protobuf:"varint,3,opt,name=job_count,json=jobCount,proto3" json:"job_count,omitempty"`
	Collapsible   bool                   `protobuf:"varint,4,opt,name=collapsible,proto3" json:"collapsible,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobDisplayGroupSummary) Reset() {
	*x = JobDisplayGroupSummary{}
	mi := &file_api_ciwi_v1_ciwi_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobDisplayGroupSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobDisplayGroupSummary) ProtoMessage() {}

func (x *JobDisplayGroupSummary) ProtoReflect() protoreflect.Message {
	mi := &file_api_ciwi_v1_ciwi_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobDisplayGroupSummary.ProtoReflect.Descriptor instead.
func (*JobDisplayGroupSummary) Descriptor() ([]byte, []int) {
	return file_api_ciwi_v1_ciwi_proto_rawDescGZIP(), []int{8}
}

func (x *JobDisplayGroupSummary) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *JobDisplayGroupSummary) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *JobDisplayGroupSummary) GetJobCount() int32 {
	if x != nil {
		return x.JobCount
	}
	return 0
}

func (x *JobDisplayGroupSummary) GetCollapsible() bool {
	if x != nil {
		return x.Collapsible
	}
	return false
}

type JobTestSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Passed        int32                  `protobuf:"varint,2,opt,name=passed,proto3" json:"passed,omitempty"`
	Failed        int32                  `protobuf:"varint,3,opt,name=failed,proto3" json:"failed,omitempty"`
	Skipped       int32                  `protobuf:"varint,4,opt,name=skipped,proto3" json:"skipped,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobTestSummary) Reset() {
	*x = JobTestSummary{}
	mi := &file_api_ciwi_v1_ciwi_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobTestSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobTestSummary) ProtoMessage() {}

func (x *JobTestSummary) ProtoReflect() protoreflect.Message {
	mi := &file_api_ciwi_v1_ciwi_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobTestSummary.ProtoReflect.Descriptor instead.
func (*JobTestSummary) Descriptor() ([]byte, []int) {
	return file_api_ciwi_v1_ciwi_proto_rawDescGZIP(), []int{9}
}

func (x *JobTestSummary) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *JobTestSummary) GetPassed() int32 {
	if x != nil {
		return x.Passed
	}
	return 0
}

func (x *JobTestSummary) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *JobTestSummary) GetSkipped() int32 {
	if x != nil {
		return x.Skipped
	}
	return 0
}

type SourceSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          string                 `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	Ref           string                 `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceSpec) Reset() {
	*x = SourceSpec{}
	mi := &file_api_ciwi_v1_ciwi_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceSpec) ProtoMessage() {}

func (x *SourceSpec) ProtoReflect() protoreflect.Message {
	mi := &file_api_ciwi_v1_ciwi_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceSpec.ProtoReflect.Descriptor instead.
func (*SourceSpec) Descriptor() ([]byte, []int) {
	return file_api_ciwi_v1_ciwi_proto_rawDescGZIP(), []int{10}
}

func (x *SourceSpec) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *SourceSpec) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

type JobExecution struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Script               string                 `protobuf:"bytes,2,opt,name=script,proto3" json:"script,omitempty"`
	Env                  map[string]string      `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RequiredCapabilities map[string]string      `protobuf:"bytes,4,rep,name=required_capabilities,json=requiredCapabilities,proto3" json:"required_capabilities,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TimeoutSeconds       int32                  `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	ArtifactGlobs        []string               `protobuf:"bytes,6,rep,name=artifact_globs,json=artifactGlobs,proto3" json:"artifact_globs,omitempty"`
	Source               *SourceSpec            `protobuf:"bytes,7,opt,name=source,proto3" json:"source,omitempty"`
	Metadata             map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Status               string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	CreatedUtc           string                 `protobuf:"bytes,10,opt,name=created_utc,json=createdUtc,proto3" json:"created_utc,omitempty"`
	StartedUtc           string                 `protobuf:"bytes,11,opt,name=started_utc,json=startedUtc,proto3" json:"started_utc,omitempty"`
	FinishedUtc          string                 `protobuf:"bytes,12,opt,name=finished_utc,json=finishedUtc,proto3" json:"finished_utc,omitempty"`
	LeasedByAgentId      string                 `protobuf:"bytes,13,opt,name=leased_by_agent_id,json=leasedByAgentId,proto3" json:"leased_by_agent_id,omitempty"`
	LeasedUtc            string                 `protobuf:"bytes,14,opt,name=leased_utc,json=leasedUtc,proto3" json:"leased_utc,omitempty"`
	ExitCode             int32                  `protobuf:"varint,15,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Error                string                 `protobuf:"bytes,16,opt,name=error,proto3" json:"error,omitempty"`
	Output               string                 `protobuf:"bytes,17,opt,name=output,proto3" json:"output,omitempty"`
	TestSummary          *JobTestSummary        `protobuf:"bytes,18,opt,name=test_summary,json=testSummary,proto3" json:"test_summary,omitempty"`
	UnmetRequirements    []string               `protobuf:"bytes,19,rep,name=unmet_requirements,json=unmetRequirements,proto3" json:"unmet_requirements,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *JobExecution) Reset() {
	*x = JobExecution{}
	mi := &file_api_ciwi_v1_ciwi_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobExecution) ProtoMessage() {}

func (x *JobExecution) ProtoReflect() protoreflect.Message {
	mi := &file_api_ciwi_v1_ciwi_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobExecution.ProtoReflect.Descriptor instead.
func (*JobExecution) Descriptor() ([]byte, []int) {
	return file_api_ciwi_v1_ciwi_proto_rawDescGZIP(), []int{11}
}

func (x *JobExecution) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JobExecution) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

func (x *JobExecution) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *JobExecution) GetRequiredCapabilities() map[string]string {
	if x != nil {
		return x.RequiredCapabilities
	}
	return nil
}

func (x *JobExecution) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *JobExecution) GetArtifactGlobs() []string {
	if x != nil {
		return x.ArtifactGlobs
	}
	return nil
}

func (x *JobExecution) GetSource() *SourceSpec {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *JobExecution) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *JobExecution) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JobExecution) GetCreatedUtc() string {
	if x != nil {
		return x.CreatedUtc
	}
	return ""
}

func (x *JobExecution) GetStartedUtc() string {
	if x != nil {
		return x.StartedUtc
	}
	return ""
}

func (x *JobExecution) GetFinishedUtc() string {
	if x != nil {
		return x.FinishedUtc
	}
	return ""
}

func (x *JobExecution) GetLeasedByAgentId() string {
	if x != nil {
		return x.LeasedByAgentId
	}
	return ""
}

func (x *JobExecution) GetLeasedUtc() string {
	if x != nil {
		return x.LeasedUtc
	}
	return ""
}

func (x *JobExecution) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *JobExecution) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *JobExecution) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *JobExecution) GetTestSummary() *JobTestSummary {
	if x != nil {
		return x.TestSummary
	}
	return nil
}

func (x *JobExecution) GetUnmetRequirements() []string {
	if x != nil {
		return x.UnmetRequirements
	}
	return nil
}

type ListJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	View          string                 `protobuf:"bytes,1,opt,name=view,proto3" json:"view,omitempty"`
	Max           int32                  `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsRequest) Reset() {
	*x = ListJobsRequest{}
	mi := &file_api_ciwi_v1_ciwi_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsRequest) ProtoMessage() {}

func (x *ListJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ciwi_v1_ciwi_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsRequest.ProtoReflect.Descriptor instead.
func (*ListJobsRequest) Descriptor() ([]byte, []int) {
	return file_api_ciwi_v1_ciwi_proto_rawDescGZIP(), []int{12}
}

func (x *ListJobsRequest) GetView() string {
	if x != nil {
		return x.View
	}
	return ""
}

func (x *ListJobsRequest) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *ListJobsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListJobsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListJobsResponse struct {
	state             protoimpl.MessageState    `protogen:"open.v1"`
	View              string                    `protobuf:"bytes,1,opt,name=view,proto3" json:"view,omitempty"`
	Max               int32                     `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	Total             int32                     `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	QueuedCount       int32                     `protobuf:"varint,4,opt,name=queued_count,json=queuedCount,proto3" json:"queued_count,omitempty"`
	HistoryCount      int32                     `protobuf:"varint,5,opt,name=history_count,json=historyCount,proto3" json:"history_count,omitempty"`
	QueuedGroupCount  int32                     `protobuf:"varint,6,opt,name=queued_group_count,json=queuedGroupCount,proto3" json:"queued_group_count,omitempty"`
	HistoryGroupCount int32                     `protobuf:"varint,7,opt,name=history_group_count,json=historyGroupCount,proto3" json:"history_group_count,omitempty"`
	QueuedGroups      []*JobDisplayGroupSummary `protobuf:"bytes,8,rep,name=queued_groups,json=queuedGroups,proto3" json:"queued_groups,omitempty"`
	HistoryGroups     []*JobDisplayGroupSummary `protobuf:"bytes,9,rep,name=history_groups,json=historyGroups,proto3" json:"history_groups,omitempty"`
	Offset            int32                     `protobuf:"varint,10,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit             int32                     `protobuf:"varint,11,opt,name=limit,proto3" json:"limit,omitempty"`
	JobExecutions     []*JobExecution           `protobuf:"bytes,12,rep,name=job_executions,json=jobExecutions,proto3" json:"job_executions,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListJobsResponse) Reset() {
	*x = ListJobsResponse{}
	mi := &file_api_ciwi_v1_ciwi_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsResponse) ProtoMessage() {}

func (x *ListJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ciwi_v1_ciwi_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsResponse.ProtoReflect.Descriptor instead.
func (*ListJobsResponse) Descriptor() ([]byte, []int) {
	return file_api_ciwi_v1_ciwi_proto_rawDescGZIP(), []int{13}
}

func (x *ListJobsResponse) GetView() string {
	if x != nil {
		return x.View
	}
	return ""
}

func (x *ListJobsResponse) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *ListJobsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListJobsResponse) GetQueuedCount() int32 {
	if x != nil {
		return x.QueuedCount
	}
	return 0
}

func (x *ListJobsResponse) GetHistoryCount() int32 {
	if x != nil {
		return x.HistoryCount
	}
	return 0
}

func (x *ListJobsResponse) GetQueuedGroupCount() int32 {
	if x != nil {
		return x.QueuedGroupCount
	}
	return 0
}

func (x *ListJobsResponse) GetHistoryGroupCount() int32 {
	if x != nil {
		return x.HistoryGroupCount
	}
	return 0
}

func (x *ListJobsResponse) GetQueuedGroups() []*JobDisplayGroupSummary {
	if x != nil {
		return x.QueuedGroups
	}
	return nil
}

func (x *ListJobsResponse) GetHistoryGroups() []*JobDisplayGroupSummary {
	if x != nil {
		return x.HistoryGroups
	}
	return nil
}

func (x *ListJobsResponse) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListJobsResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListJobsResponse) GetJobExecutions() []*JobExecution {
	if x != nil {
		return x.JobExecutions
	}
	return nil
}

type RunPipelineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PipelineId    string                 `protobuf:"bytes,1,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	DryRun        bool                   `protobuf:"varint,2,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunPipelineRequest) Reset() {
	*x = RunPipelineRequest{}
	mi := &file_api_ciwi_v1_ciwi_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunPipelineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunPipelineRequest) ProtoMessage() {}

func (x *RunPipelineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ciwi_v1_ciwi_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunPipelineRequest.ProtoReflect.Descriptor instead.
func (*RunPipelineRequest) Descriptor() ([]byte, []int) {
	return file_api_ciwi_v1_ciwi_proto_rawDescGZIP(), []int{14}
}

func (x *RunPipelineRequest) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *RunPipelineRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

type RunPipelineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectName   string                 `protobuf:"bytes,1,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	PipelineId    string                 `protobuf:"bytes,2,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	Enqueued      int32                  `protobuf:"varint,3,opt,name=enqueued,proto3" json:"enqueued,omitempty"`
	JobIds        []string               `protobuf:"bytes,4,rep,name=job_ids,json=jobIds,proto3" json:"job_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunPipelineResponse) Reset() {
	*x = RunPipelineResponse{}
	mi := &file_api_ciwi_v1_ciwi_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunPipelineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunPipelineResponse) ProtoMessage() {}

func (x *RunPipelineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ciwi_v1_ciwi_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunPipelineResponse.ProtoReflect.Descriptor instead.
func (*RunPipelineResponse) Descriptor() ([]byte, []int) {
	return file_api_ciwi_v1_ciwi_proto_rawDescGZIP(), []int{15}
}

func (x *RunPipelineResponse) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *RunPipelineResponse) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *RunPipelineResponse) GetEnqueued() int32 {
	if x != nil {
		return x.Enqueued
	}
	return 0
}

func (x *RunPipelineResponse) GetJobIds() []string {
	if x != nil {
		return x.JobIds
	}
	return nil
}

type ClearQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cleared       int64                  `protobuf:"varint,1,opt,name=cleared,proto3" json:"cleared,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearQueueResponse) Reset() {
	*x = ClearQueueResponse{}
	mi := &file_api_ciwi_v1_ciwi_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearQueueResponse) ProtoMessage() {}

func (x *ClearQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ciwi_v1_ciwi_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearQueueResponse.ProtoReflect.Descriptor instead.
func (*ClearQueueResponse) Descriptor() ([]byte, []int) {
	return file_api_ciwi_v1_ciwi_proto_rawDescGZIP(), []int{16}
}

func (x *ClearQueueResponse) GetCleared() int64 {
	if x != nil {
		return x.Cleared
	}
	return 0
}

type FlushHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flushed       int64                  `protobuf:"varint,1,opt,name=flushed,proto3" json:"flushed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlushHistoryResponse) Reset() {
	*x = FlushHistoryResponse{}
	mi := &file_api_ciwi_v1_ciwi_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushHistoryResponse) ProtoMessage() {}

func (x *FlushHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ciwi_v1_ciwi_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushHistoryResponse.ProtoReflect.Descriptor instead.
func (*FlushHistoryResponse) Descriptor() ([]byte, []int) {
	return file_api_ciwi_v1_ciwi_proto_rawDescGZIP(), []int{17}
}

func (x *FlushHistoryResponse) GetFlushed() int64 {
	if x != nil {
		return x.Flushed
	}
	return 0
}

type AgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRequest) Reset() {
	*x = AgentRequest{}
	mi := &file_api_ciwi_v1_ciwi_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRequest) ProtoMessage() {}

func (x *AgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ciwi_v1_ciwi_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRequest.ProtoReflect.Descriptor instead.
func (*AgentRequest) Descriptor() ([]byte, []int) {
	return file_api_ciwi_v1_ciwi_proto_rawDescGZIP(), []int{18}
}

func (x *AgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type AgentActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requested     bool                   `protobuf:"varint,1,opt,name=requested,proto3" json:"requested,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentActionResponse) Reset() {
	*x = AgentActionResponse{}
	mi := &file_api_ciwi_v1_ciwi_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentActionResponse) ProtoMessage() {}

func (x *AgentActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ciwi_v1_ciwi_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentActionResponse.ProtoReflect.Descriptor instead.
func (*AgentActionResponse) Descriptor() ([]byte, []int) {
	return file_api_ciwi_v1_ciwi_proto_rawDescGZIP(), []int{19}
}

func (x *AgentActionResponse) GetRequested() bool {
	if x != nil {
		return x.Requested
	}
	return false
}

func (x *AgentActionResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentActionResponse) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *AgentActionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RunAdhocScriptRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentId        string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Shell          string                 `protobuf:"bytes,2,opt,name=shell,proto3" json:"shell,omitempty"`
	Script         string                 `protobuf:"bytes,3,opt,name=script,proto3" json:"script,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RunAdhocScriptRequest) Reset() {
	*x = RunAdhocScriptRequest{}
	mi := &file_api_ciwi_v1_ciwi_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunAdhocScriptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunAdhocScriptRequest) ProtoMessage() {}

func (x *RunAdhocScriptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ciwi_v1_ciwi_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunAdhocScriptRequest.ProtoReflect.Descriptor instead.
func (*RunAdhocScriptRequest) Descriptor() ([]byte, []int) {
	return file_api_ciwi_v1_ciwi_proto_rawDescGZIP(), []int{20}
}

func (x *RunAdhocScriptRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RunAdhocScriptRequest) GetShell() string {
	if x != nil {
		return x.Shell
	}
	return ""
}

func (x *RunAdhocScriptRequest) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

func (x *RunAdhocScriptRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type RunAdhocScriptResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Queued         bool                   `protobuf:"varint,1,opt,name=queued,proto3" json:"queued,omitempty"`
	AgentId        string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	JobId          string                 `protobuf:"bytes,3,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Shell          string                 `protobuf:"bytes,4,opt,name=shell,proto3" json:"shell,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RunAdhocScriptResponse) Reset() {
	*x = RunAdhocScriptResponse{}
	mi := &file_api_ciwi_v1_ciwi_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunAdhocScriptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunAdhocScriptResponse) ProtoMessage() {}

func (x *RunAdhocScriptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ciwi_v1_ciwi_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunAdhocScriptResponse.ProtoReflect.Descriptor instead.
func (*RunAdhocScriptResponse) Descriptor() ([]byte, []int) {
	return file_api_ciwi_v1_ciwi_proto_rawDescGZIP(), []int{21}
}

func (x *RunAdhocScriptResponse) GetQueued() bool {
	if x != nil {
		return x.Queued
	}
	return false
}

func (x *RunAdhocScriptResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RunAdhocScriptResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *RunAdhocScriptResponse) GetShell() string {
	if x != nil {
		return x.Shell
	}
	return ""
}

func (x *RunAdhocScriptResponse) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type WatchStateRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	IntervalMs         int32                  `protobuf:"varint,1,opt,name=interval_ms,json=intervalMs,proto3" json:"interval_ms,omitempty"`
	IncludeProjects    bool                   `protobuf:"varint,2,opt,name=include_projects,json=includeProjects,proto3" json:"include_projects,omitempty"`
	IncludeAgents      bool                   `protobuf:"varint,3,opt,name=include_agents,json=includeAgents,proto3" json:"include_agents,omitempty"`
	IncludeJobsSummary bool                   `protobuf:"varint,4,opt,name=include_jobs_summary,json=includeJobsSummary,proto3" json:"include_jobs_summary,omitempty"`
	IncludeQueuedJobs  bool                   `protobuf:"varint,5,opt,name=include_queued_jobs,json=includeQueuedJobs,proto3" json:"include_queued_jobs,omitempty"`
	IncludeHistoryJobs bool                   `protobuf:"varint,6,opt,name=include_history_jobs,json=includeHistoryJobs,proto3" json:"include_history_jobs,omitempty"`
	JobsLimit          int32                  `protobuf:"varint,7,opt,name=jobs_limit,json=jobsLimit,proto3" json:"jobs_limit,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WatchStateRequest) Reset() {
	*x = WatchStateRequest{}
	mi := &file_api_ciwi_v1_ciwi_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchStateRequest) ProtoMessage() {}

func (x *WatchStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ciwi_v1_ciwi_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchStateRequest.ProtoReflect.Descriptor instead.
func (*WatchStateRequest) Descriptor() ([]byte, []int) {
	return file_api_ciwi_v1_ciwi_proto_rawDescGZIP(), []int{22}
}

func (x *WatchStateRequest) GetIntervalMs() int32 {
	if x != nil {
		return x.IntervalMs
	}
	return 0
}

func (x *WatchStateRequest) GetIncludeProjects() bool {
	if x != nil {
		return x.IncludeProjects
	}
	return false
}

func (x *WatchStateRequest) GetIncludeAgents() bool {
	if x != nil {
		return x.IncludeAgents
	}
	return false
}

func (x *WatchStateRequest) GetIncludeJobsSummary() bool {
	if x != nil {
		return x.IncludeJobsSummary
	}
	return false
}

func (x *WatchStateRequest) GetIncludeQueuedJobs() bool {
	if x != nil {
		return x.IncludeQueuedJobs
	}
	return false
}

func (x *WatchStateRequest) GetIncludeHistoryJobs() bool {
	if x != nil {
		return x.IncludeHistoryJobs
	}
	return false
}

func (x *WatchStateRequest) GetJobsLimit() int32 {
	if x != nil {
		return x.JobsLimit
	}
	return 0
}

type WatchStateEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Seq           int64                  `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	SentUtc       string                 `protobuf:"bytes,3,opt,name=sent_utc,json=sentUtc,proto3" json:"sent_utc,omitempty"`
	ServerInfo    *GetServerInfoResponse `protobuf:"bytes,4,opt,name=server_info,json=serverInfo,proto3" json:"server_info,omitempty"`
	Projects      *ListProjectsResponse  `protobuf:"bytes,5,opt,name=projects,proto3" json:"projects,omitempty"`
	Agents        *ListAgentsResponse    `protobuf:"bytes,6,opt,name=agents,proto3" json:"agents,omitempty"`
	JobsSummary   *ListJobsResponse      `protobuf:"bytes,7,opt,name=jobs_summary,json=jobsSummary,proto3" json:"jobs_summary,omitempty"`
	QueuedJobs    *ListJobsResponse      `protobuf:"bytes,8,opt,name=queued_jobs,json=queuedJobs,proto3" json:"queued_jobs,omitempty"`
	HistoryJobs   *ListJobsResponse      `protobuf:"bytes,9,opt,name=history_jobs,json=historyJobs,proto3" json:"history_jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchStateEvent) Reset() {
	*x = WatchStateEvent{}
	mi := &file_api_ciwi_v1_ciwi_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchStateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchStateEvent) ProtoMessage() {}

func (x *WatchStateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_ciwi_v1_ciwi_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchStateEvent.ProtoReflect.Descriptor instead.
func (*WatchStateEvent) Descriptor() ([]byte, []int) {
	return file_api_ciwi_v1_ciwi_proto_rawDescGZIP(), []int{23}
}

func (x *WatchStateEvent) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *WatchStateEvent) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *WatchStateEvent) GetSentUtc() string {
	if x != nil {
		return x.SentUtc
	}
	return ""
}

func (x *WatchStateEvent) GetServerInfo() *GetServerInfoResponse {
	if x != nil {
		return x.ServerInfo
	}
	return nil
}

func (x *WatchStateEvent) GetProjects() *ListProjectsResponse {
	if x != nil {
		return x.Projects
	}
	return nil
}

func (x *WatchStateEvent) GetAgents() *ListAgentsResponse {
	if x != nil {
		return x.Agents
	}
	return nil
}

func (x *WatchStateEvent) GetJobsSummary() *ListJobsResponse {
	if x != nil {
		return x.JobsSummary
	}
	return nil
}

func (x *WatchStateEvent) GetQueuedJobs() *ListJobsResponse {
	if x != nil {
		return x.QueuedJobs
	}
	return nil
}

func (x *WatchStateEvent) GetHistoryJobs() *ListJobsResponse {
	if x != nil {
		return x.HistoryJobs
	}
	return nil
}

var File_api_ciwi_v1_ciwi_proto protoreflect.FileDescriptor

const file_api_ciwi_v1_ciwi_proto_rawDesc = "" +
	"\n" +
	"\x16api/ciwi/v1/ciwi.proto\x12\aciwi.v1\x1a\x1bgoogle/protobuf/empty.proto\"\x82\x01\n" +
	"\x15GetServerInfoResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vapi_version\x18\x02 \x01(\x05R\n" +
	"apiVersion\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\"\xe4\x01\n" +
	"\x0eProjectSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vconfig_path\x18\x03 \x01(\tR\n" +
	"configPath\x12\x19\n" +
	"\brepo_url\x18\x04 \x01(\tR\arepoUrl\x12\x19\n" +
	"\brepo_ref\x18\x05 \x01(\tR\arepoRef\x12\x1f\n" +
	"\vconfig_file\x18\x06 \x01(\tR\n" +
	"configFile\x126\n" +
	"\tpipelines\x18\a \x03(\v2\x18.ciwi.v1.PipelineSummaryR\tpipelines\"\xbb\x01\n" +
	"\x0fPipelineSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vpipeline_id\x18\x02 \x01(\tR\n" +
	"pipelineId\x12\x18\n" +
	"\atrigger\x18\x03 \x01(\tR\atrigger\x12\x1d\n" +
	"\n" +
	"depends_on\x18\x04 \x03(\tR\tdependsOn\x12\x1f\n" +
	"\vsource_repo\x18\x05 \x01(\tR\n" +
	"sourceRepo\x12\x1d\n" +
	"\n" +
	"source_ref\x18\x06 \x01(\tR\tsourceRef\"K\n" +
	"\x14ListProjectsResponse\x123\n" +
	"\bprojects\x18\x01 \x03(\v2\x17.ciwi.v1.ProjectSummaryR\bprojects\"\xd4\x04\n" +
	"\tAgentInfo\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x04 \x01(\tR\x04arch\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12H\n" +
	"\fcapabilities\x18\x06 \x03(\v2$.ciwi.v1.AgentInfo.CapabilitiesEntryR\fcapabilities\x12\"\n" +
	"\rlast_seen_utc\x18\a \x01(\tR\vlastSeenUtc\x12\x1d\n" +
	"\n" +
	"recent_log\x18\b \x03(\tR\trecentLog\x12!\n" +
	"\fneeds_update\x18\t \x01(\bR\vneedsUpdate\x12#\n" +
	"\rupdate_target\x18\n" +
	" \x01(\tR\fupdateTarget\x12)\n" +
	"\x10update_requested\x18\v \x01(\bR\x0fupdateRequested\x12'\n" +
	"\x0fupdate_attempts\x18\f \x01(\x05R\x0eupdateAttempts\x125\n" +
	"\x17update_last_request_utc\x18\r \x01(\tR\x14updateLastRequestUtc\x121\n" +
	"\x15update_next_retry_utc\x18\x0e \x01(\tR\x12updateNextRetryUtc\x1a?\n" +
	"\x11CapabilitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"@\n" +
	"\x12ListAgentsResponse\x12*\n" +
	"\x06agents\x18\x01 \x03(\v2\x12.ciwi.v1.AgentInfoR\x06agents\",\n" +
	"\x0fGetAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"<\n" +
	"\x10GetAgentResponse\x12(\n" +
	"\x05agent\x18\x01 \x01(\v2\x12.ciwi.v1.AgentInfoR\x05agent\"\x80\x01\n" +
	"\x16JobDisplayGroupSummary\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x1b\n" +
	"\tjob_count\x18\x03 \x01(\x05R\bjobCount\x12 \n" +
	"\vcollapsible\x18\x04 \x01(\bR\vcollapsible\"p\n" +
	"\x0eJobTestSummary\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x16\n" +
	"\x06passed\x18\x02 \x01(\x05R\x06passed\x12\x16\n" +
	"\x06failed\x18\x03 \x01(\x05R\x06failed\x12\x18\n" +
	"\askipped\x18\x04 \x01(\x05R\askipped\"2\n" +
	"\n" +
	"SourceSpec\x12\x12\n" +
	"\x04repo\x18\x01 \x01(\tR\x04repo\x12\x10\n" +
	"\x03ref\x18\x02 \x01(\tR\x03ref\"\xc9\a\n" +
	"\fJobExecution\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06script\x18\x02 \x01(\tR\x06script\x120\n" +
	"\x03env\x18\x03 \x03(\v2\x1e.ciwi.v1.JobExecution.EnvEntryR\x03env\x12d\n" +
	"\x15required_capabilities\x18\x04 \x03(\v2/.ciwi.v1.JobExecution.RequiredCapabilitiesEntryR\x14requiredCapabilities\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x05R\x0etimeoutSeconds\x12%\n" +
	"\x0eartifact_globs\x18\x06 \x03(\tR\rartifactGlobs\x12+\n" +
	"\x06source\x18\a \x01(\v2\x13.ciwi.v1.SourceSpecR\x06source\x12?\n" +
	"\bmetadata\x18\b \x03(\v2#.ciwi.v1.JobExecution.MetadataEntryR\bmetadata\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12\x1f\n" +
	"\vcreated_utc\x18\n" +
	" \x01(\tR\n" +
	"createdUtc\x12\x1f\n" +
	"\vstarted_utc\x18\v \x01(\tR\n" +
	"startedUtc\x12!\n" +
	"\ffinished_utc\x18\f \x01(\tR\vfinishedUtc\x12+\n" +
	"\x12leased_by_agent_id\x18\r \x01(\tR\x0fleasedByAgentId\x12\x1d\n" +
	"\n" +
	"leased_utc\x18\x0e \x01(\tR\tleasedUtc\x12\x1b\n" +
	"\texit_code\x18\x0f \x01(\x05R\bexitCode\x12\x14\n" +
	"\x05error\x18\x10 \x01(\tR\x05error\x12\x16\n" +
	"\x06output\x18\x11 \x01(\tR\x06output\x12:\n" +
	"\ftest_summary\x18\x12 \x01(\v2\x17.ciwi.v1.JobTestSummaryR\vtestSummary\x12-\n" +
	"\x12unmet_requirements\x18\x13 \x03(\tR\x11unmetRequirements\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aG\n" +
	"\x19RequiredCapabilitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"e\n" +
	"\x0fListJobsRequest\x12\x12\n" +
	"\x04view\x18\x01 \x01(\tR\x04view\x12\x10\n" +
	"\x03max\x18\x02 \x01(\x05R\x03max\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\xee\x03\n" +
	"\x10ListJobsResponse\x12\x12\n" +
	"\x04view\x18\x01 \x01(\tR\x04view\x12\x10\n" +
	"\x03max\x18\x02 \x01(\x05R\x03max\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\x12!\n" +
	"\fqueued_count\x18\x04 \x01(\x05R\vqueuedCount\x12#\n" +
	"\rhistory_count\x18\x05 \x01(\x05R\fhistoryCount\x12,\n" +
	"\x12queued_group_count\x18\x06 \x01(\x05R\x10queuedGroupCount\x12.\n" +
	"\x13history_group_count\x18\a \x01(\x05R\x11historyGroupCount\x12D\n" +
	"\rqueued_groups\x18\b \x03(\v2\x1f.ciwi.v1.JobDisplayGroupSummaryR\fqueuedGroups\x12F\n" +
	"\x0ehistory_groups\x18\t \x03(\v2\x1f.ciwi.v1.JobDisplayGroupSummaryR\rhistoryGroups\x12\x16\n" +
	"\x06offset\x18\n" +
	" \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\v \x01(\x05R\x05limit\x12<\n" +
	"\x0ejob_executions\x18\f \x03(\v2\x15.ciwi.v1.JobExecutionR\rjobExecutions\"N\n" +
	"\x12RunPipelineRequest\x12\x1f\n" +
	"\vpipeline_id\x18\x01 \x01(\tR\n" +
	"pipelineId\x12\x17\n" +
	"\adry_run\x18\x02 \x01(\bR\x06dryRun\"\x8e\x01\n" +
	"\x13RunPipelineResponse\x12!\n" +
	"\fproject_name\x18\x01 \x01(\tR\vprojectName\x12\x1f\n" +
	"\vpipeline_id\x18\x02 \x01(\tR\n" +
	"pipelineId\x12\x1a\n" +
	"\benqueued\x18\x03 \x01(\x05R\benqueued\x12\x17\n" +
	"\ajob_ids\x18\x04 \x03(\tR\x06jobIds\".\n" +
	"\x12ClearQueueResponse\x12\x18\n" +
	"\acleared\x18\x01 \x01(\x03R\acleared\"0\n" +
	"\x14FlushHistoryResponse\x12\x18\n" +
	"\aflushed\x18\x01 \x01(\x03R\aflushed\")\n" +
	"\fAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"\x80\x01\n" +
	"\x13AgentActionResponse\x12\x1c\n" +
	"\trequested\x18\x01 \x01(\bR\trequested\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\x89\x01\n" +
	"\x15RunAdhocScriptRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x14\n" +
	"\x05shell\x18\x02 \x01(\tR\x05shell\x12\x16\n" +
	"\x06script\x18\x03 \x01(\tR\x06script\x12'\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\x05R\x0etimeoutSeconds\"\xa1\x01\n" +
	"\x16RunAdhocScriptResponse\x12\x16\n" +
	"\x06queued\x18\x01 \x01(\bR\x06queued\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x15\n" +
	"\x06job_id\x18\x03 \x01(\tR\x05jobId\x12\x14\n" +
	"\x05shell\x18\x04 \x01(\tR\x05shell\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x05R\x0etimeoutSeconds\"\xb9\x02\n" +
	"\x11WatchStateRequest\x12\x1f\n" +
	"\vinterval_ms\x18\x01 \x01(\x05R\n" +
	"intervalMs\x12)\n" +
	"\x10include_projects\x18\x02 \x01(\bR\x0fincludeProjects\x12%\n" +
	"\x0einclude_agents\x18\x03 \x01(\bR\rincludeAgents\x120\n" +
	"\x14include_jobs_summary\x18\x04 \x01(\bR\x12includeJobsSummary\x12.\n" +
	"\x13include_queued_jobs\x18\x05 \x01(\bR\x11includeQueuedJobs\x120\n" +
	"\x14include_history_jobs\x18\x06 \x01(\bR\x12includeHistoryJobs\x12\x1d\n" +
	"\n" +
	"jobs_limit\x18\a \x01(\x05R\tjobsLimit\"\xc4\x03\n" +
	"\x0fWatchStateEvent\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x03R\x03seq\x12\x19\n" +
	"\bsent_utc\x18\x03 \x01(\tR\asentUtc\x12?\n" +
	"\vserver_info\x18\x04 \x01(\v2\x1e.ciwi.v1.GetServerInfoResponseR\n" +
	"serverInfo\x129\n" +
	"\bprojects\x18\x05 \x01(\v2\x1d.ciwi.v1.ListProjectsResponseR\bprojects\x123\n" +
	"\x06agents\x18\x06 \x01(\v2\x1b.ciwi.v1.ListAgentsResponseR\x06agents\x12<\n" +
	"\fjobs_summary\x18\a \x01(\v2\x19.ciwi.v1.ListJobsResponseR\vjobsSummary\x12:\n" +
	"\vqueued_jobs\x18\b \x01(\v2\x19.ciwi.v1.ListJobsResponseR\n" +
	"queuedJobs\x12<\n" +
	"\fhistory_jobs\x18\t \x01(\v2\x19.ciwi.v1.ListJobsResponseR\vhistoryJobs2\xeb\x06\n" +
	"\vCiwiService\x12G\n" +
	"\rGetServerInfo\x12\x16.google.protobuf.Empty\x1a\x1e.ciwi.v1.GetServerInfoResponse\x12E\n" +
	"\fListProjects\x12\x16.google.protobuf.Empty\x1a\x1d.ciwi.v1.ListProjectsResponse\x12A\n" +
	"\n" +
	"ListAgents\x12\x16.google.protobuf.Empty\x1a\x1b.ciwi.v1.ListAgentsResponse\x12?\n" +
	"\bGetAgent\x12\x18.ciwi.v1.GetAgentRequest\x1a\x19.ciwi.v1.GetAgentResponse\x12?\n" +
	"\bListJobs\x12\x18.ciwi.v1.ListJobsRequest\x1a\x19.ciwi.v1.ListJobsResponse\x12H\n" +
	"\vRunPipeline\x12\x1b.ciwi.v1.RunPipelineRequest\x1a\x1c.ciwi.v1.RunPipelineResponse\x12A\n" +
	"\n" +
	"ClearQueue\x12\x16.google.protobuf.Empty\x1a\x1b.ciwi.v1.ClearQueueResponse\x12E\n" +
	"\fFlushHistory\x12\x16.google.protobuf.Empty\x1a\x1d.ciwi.v1.FlushHistoryResponse\x12I\n" +
	"\x12RequestAgentUpdate\x12\x15.ciwi.v1.AgentRequest\x1a\x1c.ciwi.v1.AgentActionResponse\x12O\n" +
	"\x18RequestAgentToolsRefresh\x12\x15.ciwi.v1.AgentRequest\x1a\x1c.ciwi.v1.AgentActionResponse\x12Q\n" +
	"\x0eRunAdhocScript\x12\x1e.ciwi.v1.RunAdhocScriptRequest\x1a\x1f.ciwi.v1.RunAdhocScriptResponse\x12D\n" +
	"\n" +
	"WatchState\x12\x1a.ciwi.v1.WatchStateRequest\x1a\x18.ciwi.v1.WatchStateEvent0\x01B:Z8github.com/izzyreal/ciwi/internal/server/grpcapi;grpcapib\x06proto3"

var (
	file_api_ciwi_v1_ciwi_proto_rawDescOnce sync.Once
	file_api_ciwi_v1_ciwi_proto_rawDescData []byte
)

func file_api_ciwi_v1_ciwi_proto_rawDescGZIP() []byte {
	file_api_ciwi_v1_ciwi_proto_rawDescOnce.Do(func() {
		file_api_ciwi_v1_ciwi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_ciwi_v1_ciwi_proto_rawDesc), len(file_api_ciwi_v1_ciwi_proto_rawDesc)))
	})
	return file_api_ciwi_v1_ciwi_proto_rawDescData
}

var file_api_ciwi_v1_ciwi_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_api_ciwi_v1_ciwi_proto_goTypes = []any{
	(*GetServerInfoResponse)(nil),  // 0: ciwi.v1.GetServerInfoResponse
	(*ProjectSummary)(nil),         // 1: ciwi.v1.ProjectSummary
	(*PipelineSummary)(nil),        // 2: ciwi.v1.PipelineSummary
	(*ListProjectsResponse)(nil),   // 3: ciwi.v1.ListProjectsResponse
	(*AgentInfo)(nil),              // 4: ciwi.v1.AgentInfo
	(*ListAgentsResponse)(nil),     // 5: ciwi.v1.ListAgentsResponse
	(*GetAgentRequest)(nil),        // 6: ciwi.v1.GetAgentRequest
	(*GetAgentResponse)(nil),       // 7: ciwi.v1.GetAgentResponse
	(*JobDisplayGroupSummary)(nil), // 8: ciwi.v1.JobDisplayGroupSummary
	(*JobTestSummary)(nil),         // 9: ciwi.v1.JobTestSummary
	(*SourceSpec)(nil),             // 10: ciwi.v1.SourceSpec
	(*JobExecution)(nil),           // 11: ciwi.v1.JobExecution
	(*ListJobsRequest)(nil),        // 12: ciwi.v1.ListJobsRequest
	(*ListJobsResponse)(nil),       // 13: ciwi.v1.ListJobsResponse
	(*RunPipelineRequest)(nil),     // 14: ciwi.v1.RunPipelineRequest
	(*RunPipelineResponse)(nil),    // 15: ciwi.v1.RunPipelineResponse
	(*ClearQueueResponse)(nil),     // 16: ciwi.v1.ClearQueueResponse
	(*FlushHistoryResponse)(nil),   // 17: ciwi.v1.FlushHistoryResponse
	(*AgentRequest)(nil),           // 18: ciwi.v1.AgentRequest
	(*AgentActionResponse)(nil),    // 19: ciwi.v1.AgentActionResponse
	(*RunAdhocScriptRequest)(nil),  // 20: ciwi.v1.RunAdhocScriptRequest
	(*RunAdhocScriptResponse)(nil), // 21: ciwi.v1.RunAdhocScriptResponse
	(*WatchStateRequest)(nil),      // 22: ciwi.v1.WatchStateRequest
	(*WatchStateEvent)(nil),        // 23: ciwi.v1.WatchStateEvent
	nil,                            // 24: ciwi.v1.AgentInfo.CapabilitiesEntry
	nil,                            // 25: ciwi.v1.JobExecution.EnvEntry
	nil,                            // 26: ciwi.v1.JobExecution.RequiredCapabilitiesEntry
	nil,                            // 27: ciwi.v1.JobExecution.MetadataEntry
	(*emptypb.Empty)(nil),          // 28: google.protobuf.Empty
}
var file_api_ciwi_v1_ciwi_proto_depIdxs = []int32{
	2,  // 0: ciwi.v1.ProjectSummary.pipelines:type_name -> ciwi.v1.PipelineSummary
	1,  // 1: ciwi.v1.ListProjectsResponse.projects:type_name -> ciwi.v1.ProjectSummary
	24, // 2: ciwi.v1.AgentInfo.capabilities:type_name -> ciwi.v1.AgentInfo.CapabilitiesEntry
	4,  // 3: ciwi.v1.ListAgentsResponse.agents:type_name -> ciwi.v1.AgentInfo
	4,  // 4: ciwi.v1.GetAgentResponse.agent:type_name -> ciwi.v1.AgentInfo
	25, // 5: ciwi.v1.JobExecution.env:type_name -> ciwi.v1.JobExecution.EnvEntry
	26, // 6: ciwi.v1.JobExecution.required_capabilities:type_name -> ciwi.v1.JobExecution.RequiredCapabilitiesEntry
	10, // 7: ciwi.v1.JobExecution.source:type_name -> ciwi.v1.SourceSpec
	27, // 8: ciwi.v1.JobExecution.metadata:type_name -> ciwi.v1.JobExecution.MetadataEntry
	9,  // 9: ciwi.v1.JobExecution.test_summary:type_name -> ciwi.v1.JobTestSummary
	8,  // 10: ciwi.v1.ListJobsResponse.queued_groups:type_name -> ciwi.v1.JobDisplayGroupSummary
	8,  // 11: ciwi.v1.ListJobsResponse.history_groups:type_name -> ciwi.v1.JobDisplayGroupSummary
	11, // 12: ciwi.v1.ListJobsResponse.job_executions:type_name -> ciwi.v1.JobExecution
	0,  // 13: ciwi.v1.WatchStateEvent.server_info:type_name -> ciwi.v1.GetServerInfoResponse
	3,  // 14: ciwi.v1.WatchStateEvent.projects:type_name -> ciwi.v1.ListProjectsResponse
	5,  // 15: ciwi.v1.WatchStateEvent.agents:type_name -> ciwi.v1.ListAgentsResponse
	13, // 16: ciwi.v1.WatchStateEvent.jobs_summary:type_name -> ciwi.v1.ListJobsResponse
	13, // 17: ciwi.v1.WatchStateEvent.queued_jobs:type_name -> ciwi.v1.ListJobsResponse
	13, // 18: ciwi.v1.WatchStateEvent.history_jobs:type_name -> ciwi.v1.ListJobsResponse
	28, // 19: ciwi.v1.CiwiService.GetServerInfo:input_type -> google.protobuf.Empty
	28, // 20: ciwi.v1.CiwiService.ListProjects:input_type -> google.protobuf.Empty
	28, // 21: ciwi.v1.CiwiService.ListAgents:input_type -> google.protobuf.Empty
	6,  // 22: ciwi.v1.CiwiService.GetAgent:input_type -> ciwi.v1.GetAgentRequest
	12, // 23: ciwi.v1.CiwiService.ListJobs:input_type -> ciwi.v1.ListJobsRequest
	14, // 24: ciwi.v1.CiwiService.RunPipeline:input_type -> ciwi.v1.RunPipelineRequest
	28, // 25: ciwi.v1.CiwiService.ClearQueue:input_type -> google.protobuf.Empty
	28, // 26: ciwi.v1.CiwiService.FlushHistory:input_type -> google.protobuf.Empty
	18, // 27: ciwi.v1.CiwiService.RequestAgentUpdate:input_type -> ciwi.v1.AgentRequest
	18, // 28: ciwi.v1.CiwiService.RequestAgentToolsRefresh:input_type -> ciwi.v1.AgentRequest
	20, // 29: ciwi.v1.CiwiService.RunAdhocScript:input_type -> ciwi.v1.RunAdhocScriptRequest
	22, // 30: ciwi.v1.CiwiService.WatchState:input_type -> ciwi.v1.WatchStateRequest
	0,  // 31: ciwi.v1.CiwiService.GetServerInfo:output_type -> ciwi.v1.GetServerInfoResponse
	3,  // 32: ciwi.v1.CiwiService.ListProjects:output_type -> ciwi.v1.ListProjectsResponse
	5,  // 33: ciwi.v1.CiwiService.ListAgents:output_type -> ciwi.v1.ListAgentsResponse
	7,  // 34: ciwi.v1.CiwiService.GetAgent:output_type -> ciwi.v1.GetAgentResponse
	13, // 35: ciwi.v1.CiwiService.ListJobs:output_type -> ciwi.v1.ListJobsResponse
	15, // 36: ciwi.v1.CiwiService.RunPipeline:output_type -> ciwi.v1.RunPipelineResponse
	16, // 37: ciwi.v1.CiwiService.ClearQueue:output_type -> ciwi.v1.ClearQueueResponse
	17, // 38: ciwi.v1.CiwiService.FlushHistory:output_type -> ciwi.v1.FlushHistoryResponse
	19, // 39: ciwi.v1.CiwiService.RequestAgentUpdate:output_type -> ciwi.v1.AgentActionResponse
	19, // 40: ciwi.v1.CiwiService.RequestAgentToolsRefresh:output_type -> ciwi.v1.AgentActionResponse
	21, // 41: ciwi.v1.CiwiService.RunAdhocScript:output_type -> ciwi.v1.RunAdhocScriptResponse
	23, // 42: ciwi.v1.CiwiService.WatchState:output_type -> ciwi.v1.WatchStateEvent
	31, // [31:43] is the sub-list for method output_type
	19, // [19:31] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_api_ciwi_v1_ciwi_proto_init() }
func file_api_ciwi_v1_ciwi_proto_init() {
	if File_api_ciwi_v1_ciwi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_ciwi_v1_ciwi_proto_rawDesc), len(file_api_ciwi_v1_ciwi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_ciwi_v1_ciwi_proto_goTypes,
		DependencyIndexes: file_api_ciwi_v1_ciwi_proto_depIdxs,
		MessageInfos:      file_api_ciwi_v1_ciwi_proto_msgTypes,
	}.Build()
	File_api_ciwi_v1_ciwi_proto = out.File
	file_api_ciwi_v1_ciwi_proto_goTypes = nil
	file_api_ciwi_v1_ciwi_proto_depIdxs = nil
}
