// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: api/ciwi/v1/ciwi.proto

package grpcapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CiwiService_GetServerInfo_FullMethodName            = "/ciwi.v1.CiwiService/GetServerInfo"
	CiwiService_ListProjects_FullMethodName             = "/ciwi.v1.CiwiService/ListProjects"
	CiwiService_ListAgents_FullMethodName               = "/ciwi.v1.CiwiService/ListAgents"
	CiwiService_GetAgent_FullMethodName                 = "/ciwi.v1.CiwiService/GetAgent"
	CiwiService_ListJobs_FullMethodName                 = "/ciwi.v1.CiwiService/ListJobs"
	CiwiService_RunPipeline_FullMethodName              = "/ciwi.v1.CiwiService/RunPipeline"
	CiwiService_ClearQueue_FullMethodName               = "/ciwi.v1.CiwiService/ClearQueue"
	CiwiService_FlushHistory_FullMethodName             = "/ciwi.v1.CiwiService/FlushHistory"
	CiwiService_RequestAgentUpdate_FullMethodName       = "/ciwi.v1.CiwiService/RequestAgentUpdate"
	CiwiService_RequestAgentToolsRefresh_FullMethodName = "/ciwi.v1.CiwiService/RequestAgentToolsRefresh"
	CiwiService_RunAdhocScript_FullMethodName           = "/ciwi.v1.CiwiService/RunAdhocScript"
	CiwiService_WatchState_FullMethodName               = "/ciwi.v1.CiwiService/WatchState"
)

// CiwiServiceClient is the client API for CiwiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CiwiServiceClient interface {
	GetServerInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetServerInfoResponse, error)
	ListProjects(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListProjectsResponse, error)
	ListAgents(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListAgentsResponse, error)
	GetAgent(ctx context.Context, in *GetAgentRequest, opts ...grpc.CallOption) (*GetAgentResponse, error)
	ListJobs(ctx context.Context, in *ListJobsRequest, opts ...grpc.CallOption) (*ListJobsResponse, error)
	RunPipeline(ctx context.Context, in *RunPipelineRequest, opts ...grpc.CallOption) (*RunPipelineResponse, error)
	ClearQueue(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ClearQueueResponse, error)
	FlushHistory(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*FlushHistoryResponse, error)
	RequestAgentUpdate(ctx context.Context, in *AgentRequest, opts ...grpc.CallOption) (*AgentActionResponse, error)
	RequestAgentToolsRefresh(ctx context.Context, in *AgentRequest, opts ...grpc.CallOption) (*AgentActionResponse, error)
	RunAdhocScript(ctx context.Context, in *RunAdhocScriptRequest, opts ...grpc.CallOption) (*RunAdhocScriptResponse, error)
	WatchState(ctx context.Context, in *WatchStateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchStateEvent], error)
}

type ciwiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCiwiServiceClient(cc grpc.ClientConnInterface) CiwiServiceClient {
	return &ciwiServiceClient{cc}
}

func (c *ciwiServiceClient) GetServerInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetServerInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServerInfoResponse)
	err := c.cc.Invoke(ctx, CiwiService_GetServerInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ciwiServiceClient) ListProjects(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListProjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProjectsResponse)
	err := c.cc.Invoke(ctx, CiwiService_ListProjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ciwiServiceClient) ListAgents(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListAgentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAgentsResponse)
	err := c.cc.Invoke(ctx, CiwiService_ListAgents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ciwiServiceClient) GetAgent(ctx context.Context, in *GetAgentRequest, opts ...grpc.CallOption) (*GetAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAgentResponse)
	err := c.cc.Invoke(ctx, CiwiService_GetAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ciwiServiceClient) ListJobs(ctx context.Context, in *ListJobsRequest, opts ...grpc.CallOption) (*ListJobsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListJobsResponse)
	err := c.cc.Invoke(ctx, CiwiService_ListJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ciwiServiceClient) RunPipeline(ctx context.Context, in *RunPipelineRequest, opts ...grpc.CallOption) (*RunPipelineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunPipelineResponse)
	err := c.cc.Invoke(ctx, CiwiService_RunPipeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ciwiServiceClient) ClearQueue(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ClearQueueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClearQueueResponse)
	err := c.cc.Invoke(ctx, CiwiService_ClearQueue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ciwiServiceClient) FlushHistory(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*FlushHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlushHistoryResponse)
	err := c.cc.Invoke(ctx, CiwiService_FlushHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ciwiServiceClient) RequestAgentUpdate(ctx context.Context, in *AgentRequest, opts ...grpc.CallOption) (*AgentActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentActionResponse)
	err := c.cc.Invoke(ctx, CiwiService_RequestAgentUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ciwiServiceClient) RequestAgentToolsRefresh(ctx context.Context, in *AgentRequest, opts ...grpc.CallOption) (*AgentActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentActionResponse)
	err := c.cc.Invoke(ctx, CiwiService_RequestAgentToolsRefresh_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ciwiServiceClient) RunAdhocScript(ctx context.Context, in *RunAdhocScriptRequest, opts ...grpc.CallOption) (*RunAdhocScriptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunAdhocScriptResponse)
	err := c.cc.Invoke(ctx, CiwiService_RunAdhocScript_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ciwiServiceClient) WatchState(ctx context.Context, in *WatchStateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchStateEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CiwiService_ServiceDesc.Streams[0], CiwiService_WatchState_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchStateRequest, WatchStateEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CiwiService_WatchStateClient = grpc.ServerStreamingClient[WatchStateEvent]

// CiwiServiceServer is the server API for CiwiService service.
// All implementations must embed UnimplementedCiwiServiceServer
// for forward compatibility.
type CiwiServiceServer interface {
	GetServerInfo(context.Context, *emptypb.Empty) (*GetServerInfoResponse, error)
	ListProjects(context.Context, *emptypb.Empty) (*ListProjectsResponse, error)
	ListAgents(context.Context, *emptypb.Empty) (*ListAgentsResponse, error)
	GetAgent(context.Context, *GetAgentRequest) (*GetAgentResponse, error)
	ListJobs(context.Context, *ListJobsRequest) (*ListJobsResponse, error)
	RunPipeline(context.Context, *RunPipelineRequest) (*RunPipelineResponse, error)
	ClearQueue(context.Context, *emptypb.Empty) (*ClearQueueResponse, error)
	FlushHistory(context.Context, *emptypb.Empty) (*FlushHistoryResponse, error)
	RequestAgentUpdate(context.Context, *AgentRequest) (*AgentActionResponse, error)
	RequestAgentToolsRefresh(context.Context, *AgentRequest) (*AgentActionResponse, error)
	RunAdhocScript(context.Context, *RunAdhocScriptRequest) (*RunAdhocScriptResponse, error)
	WatchState(*WatchStateRequest, grpc.ServerStreamingServer[WatchStateEvent]) error
	mustEmbedUnimplementedCiwiServiceServer()
}

// UnimplementedCiwiServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCiwiServiceServer struct{}

func (UnimplementedCiwiServiceServer) GetServerInfo(context.Context, *emptypb.Empty) (*GetServerInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetServerInfo not implemented")
}
func (UnimplementedCiwiServiceServer) ListProjects(context.Context, *emptypb.Empty) (*ListProjectsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProjects not implemented")
}
func (UnimplementedCiwiServiceServer) ListAgents(context.Context, *emptypb.Empty) (*ListAgentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAgents not implemented")
}
func (UnimplementedCiwiServiceServer) GetAgent(context.Context, *GetAgentRequest) (*GetAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAgent not implemented")
}
func (UnimplementedCiwiServiceServer) ListJobs(context.Context, *ListJobsRequest) (*ListJobsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListJobs not implemented")
}
func (UnimplementedCiwiServiceServer) RunPipeline(context.Context, *RunPipelineRequest) (*RunPipelineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunPipeline not implemented")
}
func (UnimplementedCiwiServiceServer) ClearQueue(context.Context, *emptypb.Empty) (*ClearQueueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClearQueue not implemented")
}
func (UnimplementedCiwiServiceServer) FlushHistory(context.Context, *emptypb.Empty) (*FlushHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FlushHistory not implemented")
}
func (UnimplementedCiwiServiceServer) RequestAgentUpdate(context.Context, *AgentRequest) (*AgentActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestAgentUpdate not implemented")
}
func (UnimplementedCiwiServiceServer) RequestAgentToolsRefresh(context.Context, *AgentRequest) (*AgentActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestAgentToolsRefresh not implemented")
}
func (UnimplementedCiwiServiceServer) RunAdhocScript(context.Context, *RunAdhocScriptRequest) (*RunAdhocScriptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunAdhocScript not implemented")
}
func (UnimplementedCiwiServiceServer) WatchState(*WatchStateRequest, grpc.ServerStreamingServer[WatchStateEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchState not implemented")
}
func (UnimplementedCiwiServiceServer) mustEmbedUnimplementedCiwiServiceServer() {}
func (UnimplementedCiwiServiceServer) testEmbeddedByValue()                     {}

// UnsafeCiwiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CiwiServiceServer will
// result in compilation errors.
type UnsafeCiwiServiceServer interface {
	mustEmbedUnimplementedCiwiServiceServer()
}

func RegisterCiwiServiceServer(s grpc.ServiceRegistrar, srv CiwiServiceServer) {
	// If the following call panics, it indicates UnimplementedCiwiServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CiwiService_ServiceDesc, srv)
}

func _CiwiService_GetServerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CiwiServiceServer).GetServerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CiwiService_GetServerInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CiwiServiceServer).GetServerInfo(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CiwiService_ListProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CiwiServiceServer).ListProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CiwiService_ListProjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CiwiServiceServer).ListProjects(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CiwiService_ListAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CiwiServiceServer).ListAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CiwiService_ListAgents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CiwiServiceServer).ListAgents(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CiwiService_GetAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CiwiServiceServer).GetAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CiwiService_GetAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CiwiServiceServer).GetAgent(ctx, req.(*GetAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CiwiService_ListJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CiwiServiceServer).ListJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CiwiService_ListJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CiwiServiceServer).ListJobs(ctx, req.(*ListJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CiwiService_RunPipeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunPipelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CiwiServiceServer).RunPipeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CiwiService_RunPipeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CiwiServiceServer).RunPipeline(ctx, req.(*RunPipelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CiwiService_ClearQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CiwiServiceServer).ClearQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CiwiService_ClearQueue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CiwiServiceServer).ClearQueue(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CiwiService_FlushHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CiwiServiceServer).FlushHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CiwiService_FlushHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CiwiServiceServer).FlushHistory(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CiwiService_RequestAgentUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CiwiServiceServer).RequestAgentUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CiwiService_RequestAgentUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CiwiServiceServer).RequestAgentUpdate(ctx, req.(*AgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CiwiService_RequestAgentToolsRefresh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CiwiServiceServer).RequestAgentToolsRefresh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CiwiService_RequestAgentToolsRefresh_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CiwiServiceServer).RequestAgentToolsRefresh(ctx, req.(*AgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CiwiService_RunAdhocScript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunAdhocScriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CiwiServiceServer).RunAdhocScript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CiwiService_RunAdhocScript_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CiwiServiceServer).RunAdhocScript(ctx, req.(*RunAdhocScriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CiwiService_WatchState_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchStateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CiwiServiceServer).WatchState(m, &grpc.GenericServerStream[WatchStateRequest, WatchStateEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CiwiService_WatchStateServer = grpc.ServerStreamingServer[WatchStateEvent]

// CiwiService_ServiceDesc is the grpc.ServiceDesc for CiwiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CiwiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ciwi.v1.CiwiService",
	HandlerType: (*CiwiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetServerInfo",
			Handler:    _CiwiService_GetServerInfo_Handler,
		},
		{
			MethodName: "ListProjects",
			Handler:    _CiwiService_ListProjects_Handler,
		},
		{
			MethodName: "ListAgents",
			Handler:    _CiwiService_ListAgents_Handler,
		},
		{
			MethodName: "GetAgent",
			Handler:    _CiwiService_GetAgent_Handler,
		},
		{
			MethodName: "ListJobs",
			Handler:    _CiwiService_ListJobs_Handler,
		},
		{
			MethodName: "RunPipeline",
			Handler:    _CiwiService_RunPipeline_Handler,
		},
		{
			MethodName: "ClearQueue",
			Handler:    _CiwiService_ClearQueue_Handler,
		},
		{
			MethodName: "FlushHistory",
			Handler:    _CiwiService_FlushHistory_Handler,
		},
		{
			MethodName: "RequestAgentUpdate",
			Handler:    _CiwiService_RequestAgentUpdate_Handler,
		},
		{
			MethodName: "RequestAgentToolsRefresh",
			Handler:    _CiwiService_RequestAgentToolsRefresh_Handler,
		},
		{
			MethodName: "RunAdhocScript",
			Handler:    _CiwiService_RunAdhocScript_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchState",
			Handler:       _CiwiService_WatchState_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/ciwi/v1/ciwi.proto",
}
