// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: ciwi/native/v1/ciwi.proto

package cnpv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusCode int32

const (
	StatusCode_STATUS_CODE_UNSPECIFIED         StatusCode = 0
	StatusCode_STATUS_CODE_INVALID_ARGUMENT    StatusCode = 1
	StatusCode_STATUS_CODE_NOT_FOUND           StatusCode = 2
	StatusCode_STATUS_CODE_CONFLICT            StatusCode = 3
	StatusCode_STATUS_CODE_FAILED_PRECONDITION StatusCode = 4
	StatusCode_STATUS_CODE_UNAVAILABLE         StatusCode = 5
	StatusCode_STATUS_CODE_UNSUPPORTED         StatusCode = 6
	StatusCode_STATUS_CODE_INTERNAL            StatusCode = 7
)

// Enum value maps for StatusCode.
var (
	StatusCode_name = map[int32]string{
		0: "STATUS_CODE_UNSPECIFIED",
		1: "STATUS_CODE_INVALID_ARGUMENT",
		2: "STATUS_CODE_NOT_FOUND",
		3: "STATUS_CODE_CONFLICT",
		4: "STATUS_CODE_FAILED_PRECONDITION",
		5: "STATUS_CODE_UNAVAILABLE",
		6: "STATUS_CODE_UNSUPPORTED",
		7: "STATUS_CODE_INTERNAL",
	}
	StatusCode_value = map[string]int32{
		"STATUS_CODE_UNSPECIFIED":         0,
		"STATUS_CODE_INVALID_ARGUMENT":    1,
		"STATUS_CODE_NOT_FOUND":           2,
		"STATUS_CODE_CONFLICT":            3,
		"STATUS_CODE_FAILED_PRECONDITION": 4,
		"STATUS_CODE_UNAVAILABLE":         5,
		"STATUS_CODE_UNSUPPORTED":         6,
		"STATUS_CODE_INTERNAL":            7,
	}
)

func (x StatusCode) Enum() *StatusCode {
	p := new(StatusCode)
	*p = x
	return p
}

func (x StatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_ciwi_native_v1_ciwi_proto_enumTypes[0].Descriptor()
}

func (StatusCode) Type() protoreflect.EnumType {
	return &file_ciwi_native_v1_ciwi_proto_enumTypes[0]
}

func (x StatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusCode.Descriptor instead.
func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return file_ciwi_native_v1_ciwi_proto_rawDescGZIP(), []int{0}
}

type ChangeTopic int32

const (
	ChangeTopic_CHANGE_TOPIC_UNSPECIFIED ChangeTopic = 0
	ChangeTopic_CHANGE_TOPIC_SERVER      ChangeTopic = 1
	ChangeTopic_CHANGE_TOPIC_PROJECTS    ChangeTopic = 2
	ChangeTopic_CHANGE_TOPIC_AGENTS      ChangeTopic = 3
	ChangeTopic_CHANGE_TOPIC_QUEUE       ChangeTopic = 4
	ChangeTopic_CHANGE_TOPIC_HISTORY     ChangeTopic = 5
	ChangeTopic_CHANGE_TOPIC_UPDATES     ChangeTopic = 6
	ChangeTopic_CHANGE_TOPIC_VAULT       ChangeTopic = 7
)

// Enum value maps for ChangeTopic.
var (
	ChangeTopic_name = map[int32]string{
		0: "CHANGE_TOPIC_UNSPECIFIED",
		1: "CHANGE_TOPIC_SERVER",
		2: "CHANGE_TOPIC_PROJECTS",
		3: "CHANGE_TOPIC_AGENTS",
		4: "CHANGE_TOPIC_QUEUE",
		5: "CHANGE_TOPIC_HISTORY",
		6: "CHANGE_TOPIC_UPDATES",
		7: "CHANGE_TOPIC_VAULT",
	}
	ChangeTopic_value = map[string]int32{
		"CHANGE_TOPIC_UNSPECIFIED": 0,
		"CHANGE_TOPIC_SERVER":      1,
		"CHANGE_TOPIC_PROJECTS":    2,
		"CHANGE_TOPIC_AGENTS":      3,
		"CHANGE_TOPIC_QUEUE":       4,
		"CHANGE_TOPIC_HISTORY":     5,
		"CHANGE_TOPIC_UPDATES":     6,
		"CHANGE_TOPIC_VAULT":       7,
	}
)

func (x ChangeTopic) Enum() *ChangeTopic {
	p := new(ChangeTopic)
	*p = x
	return p
}

func (x ChangeTopic) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChangeTopic) Descriptor() protoreflect.EnumDescriptor {
	return file_ciwi_native_v1_ciwi_proto_enumTypes[1].Descriptor()
}

func (ChangeTopic) Type() protoreflect.EnumType {
	return &file_ciwi_native_v1_ciwi_proto_enumTypes[1]
}

func (x ChangeTopic) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChangeTopic.Descriptor instead.
func (ChangeTopic) EnumDescriptor() ([]byte, []int) {
	return file_ciwi_native_v1_ciwi_proto_rawDescGZIP(), []int{1}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_ciwi_native_v1_ciwi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_ciwi_native_v1_ciwi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_ciwi_native_v1_ciwi_proto_rawDescGZIP(), []int{0}
}

type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientName    string                 `protobuf:"bytes,1,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	ClientVersion string                 `protobuf:"bytes,2,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	Capabilities  []string               `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_ciwi_native_v1_ciwi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_ciwi_native_v1_ciwi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_ciwi_native_v1_ciwi_proto_rawDescGZIP(), []int{1}
}

func (x *Hello) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *Hello) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *Hello) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type Welcome struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ServerName       string                 `protobuf:"bytes,1,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	ServerVersion    string                 `protobuf:"bytes,2,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	ServerInstanceId string                 `protobuf:"bytes,3,opt,name=server_instance_id,json=serverInstanceId,proto3" json:"server_instance_id,omitempty"`
	Capabilities     []string               `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Welcome) Reset() {
	*x = Welcome{}
	mi := &file_ciwi_native_v1_ciwi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Welcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Welcome) ProtoMessage() {}

func (x *Welcome) ProtoReflect() protoreflect.Message {
	mi := &file_ciwi_native_v1_ciwi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Welcome.ProtoReflect.Descriptor instead.
func (*Welcome) Descriptor() ([]byte, []int) {
	return file_ciwi_native_v1_ciwi_proto_rawDescGZIP(), []int{2}
}

func (x *Welcome) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *Welcome) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

func (x *Welcome) GetServerInstanceId() string {
	if x != nil {
		return x.ServerInstanceId
	}
	return ""
}

func (x *Welcome) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type RequestMetadata struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestId      string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	TimeoutMs      uint32                 `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RequestMetadata) Reset() {
	*x = RequestMetadata{}
	mi := &file_ciwi_native_v1_ciwi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMetadata) ProtoMessage() {}

func (x *RequestMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_ciwi_native_v1_ciwi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMetadata.ProtoReflect.Descriptor instead.
func (*RequestMetadata) Descriptor() ([]byte, []int) {
	return file_ciwi_native_v1_ciwi_proto_rawDescGZIP(), []int{3}
}

func (x *RequestMetadata) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RequestMetadata) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *RequestMetadata) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type ErrorStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          StatusCode             `protobuf:"varint,1,opt,name=code,proto3,enum=ciwi.native.v1.StatusCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorStatus) Reset() {
	*x = ErrorStatus{}
	mi := &file_ciwi_native_v1_ciwi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorStatus) ProtoMessage() {}

func (x *ErrorStatus) ProtoReflect() protoreflect.Message {
	mi := &file_ciwi_native_v1_ciwi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorStatus.ProtoReflect.Descriptor instead.
func (*ErrorStatus) Descriptor() ([]byte, []int) {
	return file_ciwi_native_v1_ciwi_proto_rawDescGZIP(), []int{4}
}

func (x *ErrorStatus) GetCode() StatusCode {
	if x != nil {
		return x.Code
	}
	return StatusCode_STATUS_CODE_UNSPECIFIED
}

func (x *ErrorStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ServerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ApiVersion    uint32                 `protobuf:"varint,2,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Hostname      string                 `protobuf:"bytes,4,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerInfo) Reset() {
	*x = ServerInfo{}
	mi := &file_ciwi_native_v1_ciwi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfo) ProtoMessage() {}

func (x *ServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ciwi_native_v1_ciwi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfo.ProtoReflect.Descriptor instead.
func (*ServerInfo) Descriptor() ([]byte, []int) {
	return file_ciwi_native_v1_ciwi_proto_rawDescGZIP(), []int{5}
}

func (x *ServerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServerInfo) GetApiVersion() uint32 {
	if x != nil {
		return x.ApiVersion
	}
	return 0
}

func (x *ServerInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServerInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type PipelineSummary struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PipelineId     string                 `protobuf:"bytes,2,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	Trigger        string                 `protobuf:"bytes,3,opt,name=trigger,proto3" json:"trigger,omitempty"`
	DependsOn      []string               `protobuf:"bytes,4,rep,name=depends_on,json=dependsOn,proto3" json:"depends_on,omitempty"`
	SourceRepo     string                 `protobuf:"bytes,5,opt,name=source_repo,json=sourceRepo,proto3" json:"source_repo,omitempty"`
	SourceRef      string                 `protobuf:"bytes,6,opt,name=source_ref,json=sourceRef,proto3" json:"source_ref,omitempty"`
	SupportsDryRun bool                   `protobuf:"varint,7,opt,name=supports_dry_run,json=supportsDryRun,proto3" json:"supports_dry_run,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PipelineSummary) Reset() {
	*x = PipelineSummary{}
	mi := &file_ciwi_native_v1_ciwi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineSummary) ProtoMessage() {}

func (x *PipelineSummary) ProtoReflect() protoreflect.Message {
	mi := &file_ciwi_native_v1_ciwi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineSummary.ProtoReflect.Descriptor instead.
func (*PipelineSummary) Descriptor() ([]byte, []int) {
	return file_ciwi_native_v1_ciwi_proto_rawDescGZIP(), []int{6}
}

func (x *PipelineSummary) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PipelineSummary) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *PipelineSummary) GetTrigger() string {
	if x != nil {
		return x.Trigger
	}
	return ""
}

func (x *PipelineSummary) GetDependsOn() []string {
	if x != nil {
		return x.DependsOn
	}
	return nil
}

func (x *PipelineSummary) GetSourceRepo() string {
	if x != nil {
		return x.SourceRepo
	}
	return ""
}

func (x *PipelineSummary) GetSourceRef() string {
	if x != nil {
		return x.SourceRef
	}
	return ""
}

func (x *PipelineSummary) GetSupportsDryRun() bool {
	if x != nil {
		return x.SupportsDryRun
	}
	return false
}

type PipelineChainSummary struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Pipelines         []string               `protobuf:"bytes,3,rep,name=pipelines,proto3" json:"pipelines,omitempty"`
	SupportsDryRun    bool                   `protobuf:"varint,4,opt,name=supports_dry_run,json=supportsDryRun,proto3" json:"supports_dry_run,omitempty"`
	VersionPipelineId int64                  `protobuf:"varint,5,opt,name=version_pipeline_id,json=versionPipelineId,proto3" json:"version_pipeline_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PipelineChainSummary) Reset() {
	*x = PipelineChainSummary{}
	mi := &file_ciwi_native_v1_ciwi_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineChainSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineChainSummary) ProtoMessage() {}

func (x *PipelineChainSummary) ProtoReflect() protoreflect.Message {
	mi := &file_ciwi_native_v1_ciwi_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineChainSummary.ProtoReflect.Descriptor instead.
func (*PipelineChainSummary) Descriptor() ([]byte, []int) {
	return file_ciwi_native_v1_ciwi_proto_rawDescGZIP(), []int{7}
}

func (x *PipelineChainSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PipelineChainSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PipelineChainSummary) GetPipelines() []string {
	if x != nil {
		return x.Pipelines
	}
	return nil
}

func (x *PipelineChainSummary) GetSupportsDryRun() bool {
	if x != nil {
		return x.SupportsDryRun
	}
	return false
}

func (x *PipelineChainSummary) GetVersionPipelineId() int64 {
	if x != nil {
		return x.VersionPipelineId
	}
	return 0
}

type ProjectSummary struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	Id             int64                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SourceKind     string                  `protobuf:"bytes,3,opt,name=source_kind,json=sourceKind,proto3" json:"source_kind,omitempty"`
	ConfigPath     string                  `protobuf:"bytes,4,opt,name=config_path,json=configPath,proto3" json:"config_path,omitempty"`
	RepoUrl        string                  `protobuf:"bytes,5,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"`
	RepoRef        string                  `protobuf:"bytes,6,opt,name=repo_ref,json=repoRef,proto3" json:"repo_ref,omitempty"`
	ConfigFile     string                  `protobuf:"bytes,7,opt,name=config_file,json=configFile,proto3" json:"config_file,omitempty"`
	LoadedCommit   string                  `protobuf:"bytes,8,opt,name=loaded_commit,json=loadedCommit,proto3" json:"loaded_commit,omitempty"`
	UpdatedUnixMs  int64                   `protobuf:"varint,9,opt,name=updated_unix_ms,json=updatedUnixMs,proto3" json:"updated_unix_ms,omitempty"`
	Pipelines      []*PipelineSummary      `protobuf:"bytes,10,rep,name=pipelines,proto3" json:"pipelines,omitempty"`
	PipelineChains []*PipelineChainSummary `protobuf:"bytes,11,rep,name=pipeline_chains,json=pipelineChains,proto3" json:"pipeline_chains,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProjectSummary) Reset() {
	*x = ProjectSummary{}
	mi := &file_ciwi_native_v1_ciwi_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectSummary) ProtoMessage() {}

func (x *ProjectSummary) ProtoReflect() protoreflect.Message {
	mi := &file_ciwi_native_v1_ciwi_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectSummary.ProtoReflect.Descriptor instead.
func (*ProjectSummary) Descriptor() ([]byte, []int) {
	return file_ciwi_native_v1_ciwi_proto_rawDescGZIP(), []int{8}
}

func (x *ProjectSummary) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProjectSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProjectSummary) GetSourceKind() string {
	if x != nil {
		return x.SourceKind
	}
	return ""
}

func (x *ProjectSummary) GetConfigPath() string {
	if x != nil {
		return x.ConfigPath
	}
	return ""
}

func (x *ProjectSummary) GetRepoUrl() string {
	if x != nil {
		return x.RepoUrl
	}
	return ""
}

func (x *ProjectSummary) GetRepoRef() string {
	if x != nil {
		return x.RepoRef
	}
	return ""
}

func (x *ProjectSummary) GetConfigFile() string {
	if x != nil {
		return x.ConfigFile
	}
	return ""
}

func (x *ProjectSummary) GetLoadedCommit() string {
	if x != nil {
		return x.LoadedCommit
	}
	return ""
}

func (x *ProjectSummary) GetUpdatedUnixMs() int64 {
	if x != nil {
		return x.UpdatedUnixMs
	}
	return 0
}

func (x *ProjectSummary) GetPipelines() []*PipelineSummary {
	if x != nil {
		return x.Pipelines
	}
	return nil
}

func (x *ProjectSummary) GetPipelineChains() []*PipelineChainSummary {
	if x != nil {
		return x.PipelineChains
	}
	return nil
}

type ProjectList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []*ProjectSummary      `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectList) Reset() {
	*x = ProjectList{}
	mi := &file_ciwi_native_v1_ciwi_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectList) ProtoMessage() {}

func (x *ProjectList) ProtoReflect() protoreflect.Message {
	mi := &file_ciwi_native_v1_ciwi_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectList.ProtoReflect.Descriptor instead.
func (*ProjectList) Descriptor() ([]byte, []int) {
	return file_ciwi_native_v1_ciwi_proto_rawDescGZIP(), []int{9}
}

func (x *ProjectList) GetProjects() []*ProjectSummary {
	if x != nil {
		return x.Projects
	}
	return nil
}

type FrontPageView struct {
	state             protoimpl.MessageState  `protogen:"open.v1"`
	Server            *ServerInfo             `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Projects          []*ProjectSummary       `protobuf:"bytes,2,rep,name=projects,proto3" json:"projects,omitempty"`
	QueuedExecutions  []*ExecutionCardSummary `protobuf:"bytes,3,rep,name=queued_executions,json=queuedExecutions,proto3" json:"queued_executions,omitempty"`
	HistoryExecutions []*ExecutionCardSummary `protobuf:"bytes,4,rep,name=history_executions,json=historyExecutions,proto3" json:"history_executions,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FrontPageView) Reset() {
	*x = FrontPageView{}
	mi := &file_ciwi_native_v1_ciwi_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrontPageView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrontPageView) ProtoMessage() {}

func (x *FrontPageView) ProtoReflect() protoreflect.Message {
	mi := &file_ciwi_native_v1_ciwi_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrontPageView.ProtoReflect.Descriptor instead.
func (*FrontPageView) Descriptor() ([]byte, []int) {
	return file_ciwi_native_v1_ciwi_proto_rawDescGZIP(), []int{10}
}

func (x *FrontPageView) GetServer() *ServerInfo {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *FrontPageView) GetProjects() []*ProjectSummary {
	if x != nil {
		return x.Projects
	}
	return nil
}

func (x *FrontPageView) GetQueuedExecutions() []*ExecutionCardSummary {
	if x != nil {
		return x.QueuedExecutions
	}
	return nil
}

func (x *FrontPageView) GetHistoryExecutions() []*ExecutionCardSummary {
	if x != nil {
		return x.HistoryExecutions
	}
	return nil
}

type ProjectDetailsView struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Project       *ProjectSummary           `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Pipelines     []*ProjectPipelineDetails `protobuf:"bytes,2,rep,name=pipelines,proto3" json:"pipelines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectDetailsView) Reset() {
	*x = ProjectDetailsView{}
	mi := &file_ciwi_native_v1_ciwi_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectDetailsView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectDetailsView) ProtoMessage() {}

func (x *ProjectDetailsView) ProtoReflect() protoreflect.Message {
	mi := &file_ciwi_native_v1_ciwi_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectDetailsView.ProtoReflect.Descriptor instead.
func (*ProjectDetailsView) Descriptor() ([]byte, []int) {
	return file_ciwi_native_v1_ciwi_proto_rawDescGZIP(), []int{11}
}

func (x *ProjectDetailsView) GetProject() *ProjectSummary {
	if x != nil {
		return x.Project
	}
	return nil
}

func (x *ProjectDetailsView) GetPipelines() []*ProjectPipelineDetails {
	if x != nil {
		return x.Pipelines
	}
	return nil
}

type ProjectPipelineDetails struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PipelineId     string                 `protobuf:"bytes,2,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	Trigger        string                 `protobuf:"bytes,3,opt,name=trigger,proto3" json:"trigger,omitempty"`
	DependsOn      []string               `protobuf:"bytes,4,rep,name=depends_on,json=dependsOn,proto3" json:"depends_on,omitempty"`
	Dependencies   string                 `protobuf:"bytes,5,opt,name=dependencies,proto3" json:"dependencies,omitempty"`
	JobsCount      uint32                 `protobuf:"varint,6,opt,name=jobs_count,json=jobsCount,proto3" json:"jobs_count,omitempty"`
	SupportsDryRun bool                   `protobuf:"varint,7,opt,name=supports_dry_run,json=supportsDryRun,proto3" json:"supports_dry_run,omitempty"`
	Jobs           []*ProjectJobDetails   `protobuf:"bytes,8,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProjectPipelineDetails) Reset() {
	*x = ProjectPipelineDetails{}
	mi := &file_ciwi_native_v1_ciwi_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectPipelineDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectPipelineDetails) ProtoMessage() {}

func (x *ProjectPipelineDetails) ProtoReflect() protoreflect.Message {
	mi := &file_ciwi_native_v1_ciwi_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectPipelineDetails.ProtoReflect.Descriptor instead.
func (*ProjectPipelineDetails) Descriptor() ([]byte, []int) {
	return file_ciwi_native_v1_ciwi_proto_rawDescGZIP(), []int{12}
}

func (x *ProjectPipelineDetails) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProjectPipelineDetails) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *ProjectPipelineDetails) GetTrigger() string {
	if x != nil {
		return x.Trigger
	}
	return ""
}

func (x *ProjectPipelineDetails) GetDependsOn() []string {
	if x != nil {
		return x.DependsOn
	}
	return nil
}

func (x *ProjectPipelineDetails) GetDependencies() string {
	if x != nil {
		return x.Dependencies
	}
	return ""
}

func (x *ProjectPipelineDetails) GetJobsCount() uint32 {
	if x != nil {
		return x.JobsCount
	}
	return 0
}

func (x *ProjectPipelineDetails) GetSupportsDryRun() bool {
	if x != nil {
		return x.SupportsDryRun
	}
	return false
}

func (x *ProjectPipelineDetails) GetJobs() []*ProjectJobDetails {
	if x != nil {
		return x.Jobs
	}
	return nil
}

type ProjectJobDetails struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Needs          []string               `protobuf:"bytes,2,rep,name=needs,proto3" json:"needs,omitempty"`
	NeedsLabel     string                 `protobuf:"bytes,3,opt,name=needs_label,json=needsLabel,proto3" json:"needs_label,omitempty"`
	RunsOnLabel    string                 `protobuf:"bytes,4,opt,name=runs_on_label,json=runsOnLabel,proto3" json:"runs_on_label,omitempty"`
	ToolsLabel     string                 `protobuf:"bytes,5,opt,name=tools_label,json=toolsLabel,proto3" json:"tools_label,omitempty"`
	TimeoutSeconds uint32                 `protobuf:"varint,6,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	MatrixCount    uint32                 `protobuf:"varint,7,opt,name=matrix_count,json=matrixCount,proto3" json:"matrix_count,omitempty"`
	StepsCount     uint32                 `protobuf:"varint,8,opt,name=steps_count,json=stepsCount,proto3" json:"steps_count,omitempty"`
	Steps          []*ProjectStepDetails  `protobuf:"bytes,9,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProjectJobDetails) Reset() {
	*x = ProjectJobDetails{}
	mi := &file_ciwi_native_v1_ciwi_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectJobDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectJobDetails) ProtoMessage() {}

func (x *ProjectJobDetails) ProtoReflect() protoreflect.Message {
	mi := &file_ciwi_native_v1_ciwi_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectJobDetails.ProtoReflect.Descriptor instead.
func (*ProjectJobDetails) Descriptor() ([]byte, []int) {
	return file_ciwi_native_v1_ciwi_proto_rawDescGZIP(), []int{13}
}

func (x *ProjectJobDetails) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProjectJobDetails) GetNeeds() []string {
	if x != nil {
		return x.Needs
	}
	return nil
}

func (x *ProjectJobDetails) GetNeedsLabel() string {
	if x != nil {
		return x.NeedsLabel
	}
	return ""
}

func (x *ProjectJobDetails) GetRunsOnLabel() string {
	if x != nil {
		return x.RunsOnLabel
	}
	return ""
}

func (x *ProjectJobDetails) GetToolsLabel() string {
	if x != nil {
		return x.ToolsLabel
	}
	return ""
}

func (x *ProjectJobDetails) GetTimeoutSeconds() uint32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *ProjectJobDetails) GetMatrixCount() uint32 {
	if x != nil {
		return x.MatrixCount
	}
	return 0
}

func (x *ProjectJobDetails) GetStepsCount() uint32 {
	if x != nil {
		return x.StepsCount
	}
	return 0
}

func (x *ProjectJobDetails) GetSteps() []*ProjectStepDetails {
	if x != nil {
		return x.Steps
	}
	return nil
}

type ProjectStepDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Position      uint32                 `protobuf:"varint,2,opt,name=position,proto3" json:"position,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Command       string                 `protobuf:"bytes,5,opt,name=command,proto3" json:"command,omitempty"`
	SkipDryRun    bool                   `protobuf:"varint,6,opt,name=skip_dry_run,json=skipDryRun,proto3" json:"skip_dry_run,omitempty"`
	Environment   []string               `protobuf:"bytes,7,rep,name=environment,proto3" json:"environment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectStepDetails) Reset() {
	*x = ProjectStepDetails{}
	mi := &file_ciwi_native_v1_ciwi_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectStepDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectStepDetails) ProtoMessage() {}

func (x *ProjectStepDetails) ProtoReflect() protoreflect.Message {
	mi := &file_ciwi_native_v1_ciwi_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectStepDetails.ProtoReflect.Descriptor instead.
func (*ProjectStepDetails) Descriptor() ([]byte, []int) {
	return file_ciwi_native_v1_ciwi_proto_rawDescGZIP(), []int{14}
}

func (x *ProjectStepDetails) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ProjectStepDetails) GetPosition() uint32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *ProjectStepDetails) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProjectStepDetails) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ProjectStepDetails) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ProjectStepDetails) GetSkipDryRun() bool {
	if x != nil {
		return x.SkipDryRun
	}
	return false
}

func (x *ProjectStepDetails) GetEnvironment() []string {
	if x != nil {
		return x.Environment
	}
	return nil
}

type GetProjectDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     int64                  `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectDetailsRequest) Reset() {
	*x = GetProjectDetailsRequest{}
	mi := &file_ciwi_native_v1_ciwi_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectDetailsRequest) ProtoMessage() {}

func (x *GetProjectDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ciwi_native_v1_ciwi_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetProjectDetailsRequest) Descriptor() ([]byte, []int) {
	return file_ciwi_native_v1_ciwi_proto_rawDescGZIP(), []int{15}
}

func (x *GetProjectDetailsRequest) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

type GetJobDetailsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	JobExecutionId string                 `protobuf:"bytes,1,opt,name=job_execution_id,json=jobExecutionId,proto3" json:"job_execution_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetJobDetailsRequest) Reset() {
	*x = GetJobDetailsRequest{}
	mi := &file_ciwi_native_v1_ciwi_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobDetailsRequest) ProtoMessage() {}

func (x *GetJobDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ciwi_native_v1_ciwi_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetJobDetailsRequest) Descriptor() ([]byte, []int) {
	return file_ciwi_native_v1_ciwi_proto_rawDescGZIP(), []int{16}
}

func (x *GetJobDetailsRequest) GetJobExecutionId() string {
	if x != nil {
		return x.JobExecutionId
	}
	return ""
}

type JobDetailsView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Context       string                 `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	StatusLabel   string                 `protobuf:"bytes,5,opt,name=status_label,json=statusLabel,proto3" json:"status_label,omitempty"`
	CurrentStep   string                 `protobuf:"bytes,6,opt,name=current_step,json=currentStep,proto3" json:"current_step,omitempty"`
	Agent         string                 `protobuf:"bytes,7,opt,name=agent,proto3" json:"agent,omitempty"`
	Mode          string                 `protobuf:"bytes,8,opt,name=mode,proto3" json:"mode,omitempty"`
	Created       string                 `protobuf:"bytes,9,opt,name=created,proto3" json:"created,omitempty"`
	Started       string                 `protobuf:"bytes,10,opt,name=started,proto3" json:"started,omitempty"`
	Finished      string                 `protobuf:"bytes,11,opt,name=finished,proto3" json:"finished,omitempty"`
	Duration      string                 `protobuf:"bytes,12,opt,name=duration,proto3" json:"duration,omitempty"`
	ExitCode      string                 `protobuf:"bytes,13,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Error         string                 `protobuf:"bytes,14,opt,name=error,proto3" json:"error,omitempty"`
	Timeline      []*JobTimelineItem     `protobuf:"bytes,15,rep,name=timeline,proto3" json:"timeline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobDetailsView) Reset() {
	*x = JobDetailsView{}
	mi := &file_ciwi_native_v1_ciwi_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobDetailsView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobDetailsView) ProtoMessage() {}

func (x *JobDetailsView) ProtoReflect() protoreflect.Message {
	mi := &file_ciwi_native_v1_ciwi_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobDetailsView.ProtoReflect.Descriptor instead.
func (*JobDetailsView) Descriptor() ([]byte, []int) {
	return file_ciwi_native_v1_ciwi_proto_rawDescGZIP(), []int{17}
}

func (x *JobDetailsView) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JobDetailsView) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *JobDetailsView) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *JobDetailsView) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JobDetailsView) GetStatusLabel() string {
	if x != nil {
		return x.StatusLabel
	}
	return ""
}

func (x *JobDetailsView) GetCurrentStep() string {
	if x != nil {
		return x.CurrentStep
	}
	return ""
}

func (x *JobDetailsView) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *JobDetailsView) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *JobDetailsView) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *JobDetailsView) GetStarted() string {
	if x != nil {
		return x.Started
	}
	return ""
}

func (x *JobDetailsView) GetFinished() string {
	if x != nil {
		return x.Finished
	}
	return ""
}

func (x *JobDetailsView) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *JobDetailsView) GetExitCode() string {
	if x != nil {
		return x.ExitCode
	}
	return ""
}

func (x *JobDetailsView) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *JobDetailsView) GetTimeline() []*JobTimelineItem {
	if x != nil {
		return x.Timeline
	}
	return nil
}

type JobTimelineItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	StatusLabel   string                 `protobuf:"bytes,6,opt,name=status_label,json=statusLabel,proto3" json:"status_label,omitempty"`
	Duration      string                 `protobuf:"bytes,7,opt,name=duration,proto3" json:"duration,omitempty"`
	ExitCode      string                 `protobuf:"bytes,8,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Error         string                 `protobuf:"bytes,9,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobTimelineItem) Reset() {
	*x = JobTimelineItem{}
	mi := &file_ciwi_native_v1_ciwi_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobTimelineItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobTimelineItem) ProtoMessage() {}

func (x *JobTimelineItem) ProtoReflect() protoreflect.Message {
	mi := &file_ciwi_native_v1_ciwi_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobTimelineItem.ProtoReflect.Descriptor instead.
func (*JobTimelineItem) Descriptor() ([]byte, []int) {
	return file_ciwi_native_v1_ciwi_proto_rawDescGZIP(), []int{18}
}

func (x *JobTimelineItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JobTimelineItem) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *JobTimelineItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *JobTimelineItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *JobTimelineItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JobTimelineItem) GetStatusLabel() string {
	if x != nil {
		return x.StatusLabel
	}
	return ""
}

func (x *JobTimelineItem) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *JobTimelineItem) GetExitCode() string {
	if x != nil {
		return x.ExitCode
	}
	return ""
}

func (x *JobTimelineItem) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ExecutionSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalJobs     uint32                 `protobuf:"varint,1,opt,name=total_jobs,json=totalJobs,proto3" json:"total_jobs,omitempty"`
	Succeeded     uint32                 `protobuf:"varint,2,opt,name=succeeded,proto3" json:"succeeded,omitempty"`
	Failed        uint32                 `protobuf:"varint,3,opt,name=failed,proto3" json:"failed,omitempty"`
	InProgress    uint32                 `protobuf:"varint,4,opt,name=in_progress,json=inProgress,proto3" json:"in_progress,omitempty"`
	Waiting       uint32                 `protobuf:"varint,5,opt,name=waiting,proto3" json:"waiting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionSummary) Reset() {
	*x = ExecutionSummary{}
	mi := &file_ciwi_native_v1_ciwi_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionSummary) ProtoMessage() {}

func (x *ExecutionSummary) ProtoReflect() protoreflect.Message {
	mi := &file_ciwi_native_v1_ciwi_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionSummary.ProtoReflect.Descriptor instead.
func (*ExecutionSummary) Descriptor() ([]byte, []int) {
	return file_ciwi_native_v1_ciwi_proto_rawDescGZIP(), []int{19}
}

func (x *ExecutionSummary) GetTotalJobs() uint32 {
	if x != nil {
		return x.TotalJobs
	}
	return 0
}

func (x *ExecutionSummary) GetSucceeded() uint32 {
	if x != nil {
		return x.Succeeded
	}
	return 0
}

func (x *ExecutionSummary) GetFailed() uint32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *ExecutionSummary) GetInProgress() uint32 {
	if x != nil {
		return x.InProgress
	}
	return 0
}

func (x *ExecutionSummary) GetWaiting() uint32 {
	if x != nil {
		return x.Waiting
	}
	return 0
}

type ExecutionCardSummary struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Key             string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Kind            string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Title           string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	JobExecutionIds []string               `protobuf:"bytes,4,rep,name=job_execution_ids,json=jobExecutionIds,proto3" json:"job_execution_ids,omitempty"`
	Summary         *ExecutionSummary      `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExecutionCardSummary) Reset() {
	*x = ExecutionCardSummary{}
	mi := &file_ciwi_native_v1_ciwi_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionCardSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionCardSummary) ProtoMessage() {}

func (x *ExecutionCardSummary) ProtoReflect() protoreflect.Message {
	mi := &file_ciwi_native_v1_ciwi_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionCardSummary.ProtoReflect.Descriptor instead.
func (*ExecutionCardSummary) Descriptor() ([]byte, []int) {
	return file_ciwi_native_v1_ciwi_proto_rawDescGZIP(), []int{20}
}

func (x *ExecutionCardSummary) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ExecutionCardSummary) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ExecutionCardSummary) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ExecutionCardSummary) GetJobExecutionIds() []string {
	if x != nil {
		return x.JobExecutionIds
	}
	return nil
}

func (x *ExecutionCardSummary) GetSummary() *ExecutionSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

type RunPipelineSelection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PipelineJobId string                 `protobuf:"bytes,1,opt,name=pipeline_job_id,json=pipelineJobId,proto3" json:"pipeline_job_id,omitempty"`
	MatrixName    string                 `protobuf:"bytes,2,opt,name=matrix_name,json=matrixName,proto3" json:"matrix_name,omitempty"`
	MatrixIndex   *int32                 `protobuf:"varint,3,opt,name=matrix_index,json=matrixIndex,proto3,oneof" json:"matrix_index,omitempty"`
	DryRun        bool                   `protobuf:"varint,4,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	SourceRef     string                 `protobuf:"bytes,5,opt,name=source_ref,json=sourceRef,proto3" json:"source_ref,omitempty"`
	AgentId       string                 `protobuf:"bytes,6,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ExecutionMode string                 `protobuf:"bytes,7,opt,name=execution_mode,json=executionMode,proto3" json:"execution_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunPipelineSelection) Reset() {
	*x = RunPipelineSelection{}
	mi := &file_ciwi_native_v1_ciwi_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunPipelineSelection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunPipelineSelection) ProtoMessage() {}

func (x *RunPipelineSelection) ProtoReflect() protoreflect.Message {
	mi := &file_ciwi_native_v1_ciwi_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunPipelineSelection.ProtoReflect.Descriptor instead.
func (*RunPipelineSelection) Descriptor() ([]byte, []int) {
	return file_ciwi_native_v1_ciwi_proto_rawDescGZIP(), []int{21}
}

func (x *RunPipelineSelection) GetPipelineJobId() string {
	if x != nil {
		return x.PipelineJobId
	}
	return ""
}

func (x *RunPipelineSelection) GetMatrixName() string {
	if x != nil {
		return x.MatrixName
	}
	return ""
}

func (x *RunPipelineSelection) GetMatrixIndex() int32 {
	if x != nil && x.MatrixIndex != nil {
		return *x.MatrixIndex
	}
	return 0
}

func (x *RunPipelineSelection) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

func (x *RunPipelineSelection) GetSourceRef() string {
	if x != nil {
		return x.SourceRef
	}
	return ""
}

func (x *RunPipelineSelection) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RunPipelineSelection) GetExecutionMode() string {
	if x != nil {
		return x.ExecutionMode
	}
	return ""
}

type RunPipelineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PipelineDbId  int64                  `protobuf:"varint,1,opt,name=pipeline_db_id,json=pipelineDbId,proto3" json:"pipeline_db_id,omitempty"`
	Selection     *RunPipelineSelection  `protobuf:"bytes,2,opt,name=selection,proto3" json:"selection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunPipelineRequest) Reset() {
	*x = RunPipelineRequest{}
	mi := &file_ciwi_native_v1_ciwi_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunPipelineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunPipelineRequest) ProtoMessage() {}

func (x *RunPipelineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ciwi_native_v1_ciwi_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunPipelineRequest.ProtoReflect.Descriptor instead.
func (*RunPipelineRequest) Descriptor() ([]byte, []int) {
	return file_ciwi_native_v1_ciwi_proto_rawDescGZIP(), []int{22}
}

func (x *RunPipelineRequest) GetPipelineDbId() int64 {
	if x != nil {
		return x.PipelineDbId
	}
	return 0
}

func (x *RunPipelineRequest) GetSelection() *RunPipelineSelection {
	if x != nil {
		return x.Selection
	}
	return nil
}

type RunPipelineResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProjectName     string                 `protobuf:"bytes,1,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	PipelineId      string                 `protobuf:"bytes,2,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	Enqueued        uint32                 `protobuf:"varint,3,opt,name=enqueued,proto3" json:"enqueued,omitempty"`
	JobExecutionIds []string               `protobuf:"bytes,4,rep,name=job_execution_ids,json=jobExecutionIds,proto3" json:"job_execution_ids,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RunPipelineResult) Reset() {
	*x = RunPipelineResult{}
	mi := &file_ciwi_native_v1_ciwi_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunPipelineResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunPipelineResult) ProtoMessage() {}

func (x *RunPipelineResult) ProtoReflect() protoreflect.Message {
	mi := &file_ciwi_native_v1_ciwi_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunPipelineResult.ProtoReflect.Descriptor instead.
func (*RunPipelineResult) Descriptor() ([]byte, []int) {
	return file_ciwi_native_v1_ciwi_proto_rawDescGZIP(), []int{23}
}

func (x *RunPipelineResult) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *RunPipelineResult) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *RunPipelineResult) GetEnqueued() uint32 {
	if x != nil {
		return x.Enqueued
	}
	return 0
}

func (x *RunPipelineResult) GetJobExecutionIds() []string {
	if x != nil {
		return x.JobExecutionIds
	}
	return nil
}

type WatchChangesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchChangesRequest) Reset() {
	*x = WatchChangesRequest{}
	mi := &file_ciwi_native_v1_ciwi_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchChangesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchChangesRequest) ProtoMessage() {}

func (x *WatchChangesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ciwi_native_v1_ciwi_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchChangesRequest.ProtoReflect.Descriptor instead.
func (*WatchChangesRequest) Descriptor() ([]byte, []int) {
	return file_ciwi_native_v1_ciwi_proto_rawDescGZIP(), []int{24}
}

type ChangeEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ServerInstanceId string                 `protobuf:"bytes,1,opt,name=server_instance_id,json=serverInstanceId,proto3" json:"server_instance_id,omitempty"`
	Revision         uint64                 `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	Topics           []ChangeTopic          `protobuf:"varint,3,rep,packed,name=topics,proto3,enum=ciwi.native.v1.ChangeTopic" json:"topics,omitempty"`
	OccurredUnixMs   int64                  `protobuf:"varint,4,opt,name=occurred_unix_ms,json=occurredUnixMs,proto3" json:"occurred_unix_ms,omitempty"`
	ResyncRequired   bool                   `protobuf:"varint,5,opt,name=resync_required,json=resyncRequired,proto3" json:"resync_required,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ChangeEvent) Reset() {
	*x = ChangeEvent{}
	mi := &file_ciwi_native_v1_ciwi_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeEvent) ProtoMessage() {}

func (x *ChangeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_ciwi_native_v1_ciwi_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeEvent.ProtoReflect.Descriptor instead.
func (*ChangeEvent) Descriptor() ([]byte, []int) {
	return file_ciwi_native_v1_ciwi_proto_rawDescGZIP(), []int{25}
}

func (x *ChangeEvent) GetServerInstanceId() string {
	if x != nil {
		return x.ServerInstanceId
	}
	return ""
}

func (x *ChangeEvent) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *ChangeEvent) GetTopics() []ChangeTopic {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *ChangeEvent) GetOccurredUnixMs() int64 {
	if x != nil {
		return x.OccurredUnixMs
	}
	return 0
}

func (x *ChangeEvent) GetResyncRequired() bool {
	if x != nil {
		return x.ResyncRequired
	}
	return false
}

type Request struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Metadata *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Types that are valid to be assigned to Operation:
	//
	//	*Request_GetServerInfo
	//	*Request_ListProjects
	//	*Request_GetFrontPageView
	//	*Request_RunPipeline
	//	*Request_WatchChanges
	//	*Request_GetProjectDetails
	//	*Request_GetJobDetails
	Operation     isRequest_Operation `protobuf_oneof:"operation"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_ciwi_native_v1_ciwi_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_ciwi_native_v1_ciwi_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_ciwi_native_v1_ciwi_proto_rawDescGZIP(), []int{26}
}

func (x *Request) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Request) GetOperation() isRequest_Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *Request) GetGetServerInfo() *Empty {
	if x != nil {
		if x, ok := x.Operation.(*Request_GetServerInfo); ok {
			return x.GetServerInfo
		}
	}
	return nil
}

func (x *Request) GetListProjects() *Empty {
	if x != nil {
		if x, ok := x.Operation.(*Request_ListProjects); ok {
			return x.ListProjects
		}
	}
	return nil
}

func (x *Request) GetGetFrontPageView() *Empty {
	if x != nil {
		if x, ok := x.Operation.(*Request_GetFrontPageView); ok {
			return x.GetFrontPageView
		}
	}
	return nil
}

func (x *Request) GetRunPipeline() *RunPipelineRequest {
	if x != nil {
		if x, ok := x.Operation.(*Request_RunPipeline); ok {
			return x.RunPipeline
		}
	}
	return nil
}

func (x *Request) GetWatchChanges() *WatchChangesRequest {
	if x != nil {
		if x, ok := x.Operation.(*Request_WatchChanges); ok {
			return x.WatchChanges
		}
	}
	return nil
}

func (x *Request) GetGetProjectDetails() *GetProjectDetailsRequest {
	if x != nil {
		if x, ok := x.Operation.(*Request_GetProjectDetails); ok {
			return x.GetProjectDetails
		}
	}
	return nil
}

func (x *Request) GetGetJobDetails() *GetJobDetailsRequest {
	if x != nil {
		if x, ok := x.Operation.(*Request_GetJobDetails); ok {
			return x.GetJobDetails
		}
	}
	return nil
}

type isRequest_Operation interface {
	isRequest_Operation()
}

type Request_GetServerInfo struct {
	GetServerInfo *Empty `protobuf:"bytes,10,opt,name=get_server_info,json=getServerInfo,proto3,oneof"`
}

type Request_ListProjects struct {
	ListProjects *Empty `protobuf:"bytes,11,opt,name=list_projects,json=listProjects,proto3,oneof"`
}

type Request_GetFrontPageView struct {
	GetFrontPageView *Empty `protobuf:"bytes,12,opt,name=get_front_page_view,json=getFrontPageView,proto3,oneof"`
}

type Request_RunPipeline struct {
	RunPipeline *RunPipelineRequest `protobuf:"bytes,13,opt,name=run_pipeline,json=runPipeline,proto3,oneof"`
}

type Request_WatchChanges struct {
	WatchChanges *WatchChangesRequest `protobuf:"bytes,14,opt,name=watch_changes,json=watchChanges,proto3,oneof"`
}

type Request_GetProjectDetails struct {
	GetProjectDetails *GetProjectDetailsRequest `protobuf:"bytes,15,opt,name=get_project_details,json=getProjectDetails,proto3,oneof"`
}

type Request_GetJobDetails struct {
	GetJobDetails *GetJobDetailsRequest `protobuf:"bytes,16,opt,name=get_job_details,json=getJobDetails,proto3,oneof"`
}

func (*Request_GetServerInfo) isRequest_Operation() {}

func (*Request_ListProjects) isRequest_Operation() {}

func (*Request_GetFrontPageView) isRequest_Operation() {}

func (*Request_RunPipeline) isRequest_Operation() {}

func (*Request_WatchChanges) isRequest_Operation() {}

func (*Request_GetProjectDetails) isRequest_Operation() {}

func (*Request_GetJobDetails) isRequest_Operation() {}

type Response struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*Response_ServerInfo
	//	*Response_ProjectList
	//	*Response_FrontPageView
	//	*Response_RunPipeline
	//	*Response_Change
	//	*Response_Error
	//	*Response_ProjectDetails
	//	*Response_JobDetails
	Result        isResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_ciwi_native_v1_ciwi_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_ciwi_native_v1_ciwi_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_ciwi_native_v1_ciwi_proto_rawDescGZIP(), []int{27}
}

func (x *Response) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Response) GetResult() isResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *Response) GetServerInfo() *ServerInfo {
	if x != nil {
		if x, ok := x.Result.(*Response_ServerInfo); ok {
			return x.ServerInfo
		}
	}
	return nil
}

func (x *Response) GetProjectList() *ProjectList {
	if x != nil {
		if x, ok := x.Result.(*Response_ProjectList); ok {
			return x.ProjectList
		}
	}
	return nil
}

func (x *Response) GetFrontPageView() *FrontPageView {
	if x != nil {
		if x, ok := x.Result.(*Response_FrontPageView); ok {
			return x.FrontPageView
		}
	}
	return nil
}

func (x *Response) GetRunPipeline() *RunPipelineResult {
	if x != nil {
		if x, ok := x.Result.(*Response_RunPipeline); ok {
			return x.RunPipeline
		}
	}
	return nil
}

func (x *Response) GetChange() *ChangeEvent {
	if x != nil {
		if x, ok := x.Result.(*Response_Change); ok {
			return x.Change
		}
	}
	return nil
}

func (x *Response) GetError() *ErrorStatus {
	if x != nil {
		if x, ok := x.Result.(*Response_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *Response) GetProjectDetails() *ProjectDetailsView {
	if x != nil {
		if x, ok := x.Result.(*Response_ProjectDetails); ok {
			return x.ProjectDetails
		}
	}
	return nil
}

func (x *Response) GetJobDetails() *JobDetailsView {
	if x != nil {
		if x, ok := x.Result.(*Response_JobDetails); ok {
			return x.JobDetails
		}
	}
	return nil
}

type isResponse_Result interface {
	isResponse_Result()
}

type Response_ServerInfo struct {
	ServerInfo *ServerInfo `protobuf:"bytes,10,opt,name=server_info,json=serverInfo,proto3,oneof"`
}

type Response_ProjectList struct {
	ProjectList *ProjectList `protobuf:"bytes,11,opt,name=project_list,json=projectList,proto3,oneof"`
}

type Response_FrontPageView struct {
	FrontPageView *FrontPageView `protobuf:"bytes,12,opt,name=front_page_view,json=frontPageView,proto3,oneof"`
}

type Response_RunPipeline struct {
	RunPipeline *RunPipelineResult `protobuf:"bytes,13,opt,name=run_pipeline,json=runPipeline,proto3,oneof"`
}

type Response_Change struct {
	Change *ChangeEvent `protobuf:"bytes,14,opt,name=change,proto3,oneof"`
}

type Response_Error struct {
	Error *ErrorStatus `protobuf:"bytes,15,opt,name=error,proto3,oneof"`
}

type Response_ProjectDetails struct {
	ProjectDetails *ProjectDetailsView `protobuf:"bytes,16,opt,name=project_details,json=projectDetails,proto3,oneof"`
}

type Response_JobDetails struct {
	JobDetails *JobDetailsView `protobuf:"bytes,17,opt,name=job_details,json=jobDetails,proto3,oneof"`
}

func (*Response_ServerInfo) isResponse_Result() {}

func (*Response_ProjectList) isResponse_Result() {}

func (*Response_FrontPageView) isResponse_Result() {}

func (*Response_RunPipeline) isResponse_Result() {}

func (*Response_Change) isResponse_Result() {}

func (*Response_Error) isResponse_Result() {}

func (*Response_ProjectDetails) isResponse_Result() {}

func (*Response_JobDetails) isResponse_Result() {}

type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*ClientMessage_Hello
	//	*ClientMessage_Request
	Body          isClientMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_ciwi_native_v1_ciwi_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ciwi_native_v1_ciwi_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_ciwi_native_v1_ciwi_proto_rawDescGZIP(), []int{28}
}

func (x *ClientMessage) GetBody() isClientMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ClientMessage) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Body.(*ClientMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *ClientMessage) GetRequest() *Request {
	if x != nil {
		if x, ok := x.Body.(*ClientMessage_Request); ok {
			return x.Request
		}
	}
	return nil
}

type isClientMessage_Body interface {
	isClientMessage_Body()
}

type ClientMessage_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type ClientMessage_Request struct {
	Request *Request `protobuf:"bytes,2,opt,name=request,proto3,oneof"`
}

func (*ClientMessage_Hello) isClientMessage_Body() {}

func (*ClientMessage_Request) isClientMessage_Body() {}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*ServerMessage_Welcome
	//	*ServerMessage_Response
	Body          isServerMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_ciwi_native_v1_ciwi_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ciwi_native_v1_ciwi_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_ciwi_native_v1_ciwi_proto_rawDescGZIP(), []int{29}
}

func (x *ServerMessage) GetBody() isServerMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ServerMessage) GetWelcome() *Welcome {
	if x != nil {
		if x, ok := x.Body.(*ServerMessage_Welcome); ok {
			return x.Welcome
		}
	}
	return nil
}

func (x *ServerMessage) GetResponse() *Response {
	if x != nil {
		if x, ok := x.Body.(*ServerMessage_Response); ok {
			return x.Response
		}
	}
	return nil
}

type isServerMessage_Body interface {
	isServerMessage_Body()
}

type ServerMessage_Welcome struct {
	Welcome *Welcome `protobuf:"bytes,1,opt,name=welcome,proto3,oneof"`
}

type ServerMessage_Response struct {
	Response *Response `protobuf:"bytes,2,opt,name=response,proto3,oneof"`
}

func (*ServerMessage_Welcome) isServerMessage_Body() {}

func (*ServerMessage_Response) isServerMessage_Body() {}

var File_ciwi_native_v1_ciwi_proto protoreflect.FileDescriptor

const file_ciwi_native_v1_ciwi_proto_rawDesc = "" +
	"\n" +
	"\x19ciwi/native/v1/ciwi.proto\x12\x0eciwi.native.v1\"\a\n" +
	"\x05Empty\"s\n" +
	"\x05Hello\x12\x1f\n" +
	"\vclient_name\x18\x01 \x01(\tR\n" +
	"clientName\x12%\n" +
	"\x0eclient_version\x18\x02 \x01(\tR\rclientVersion\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\"\xa3\x01\n" +
	"\aWelcome\x12\x1f\n" +
	"\vserver_name\x18\x01 \x01(\tR\n" +
	"serverName\x12%\n" +
	"\x0eserver_version\x18\x02 \x01(\tR\rserverVersion\x12,\n" +
	"\x12server_instance_id\x18\x03 \x01(\tR\x10serverInstanceId\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\"x\n" +
	"\x0fRequestMetadata\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\rR\ttimeoutMs\"W\n" +
	"\vErrorStatus\x12.\n" +
	"\x04code\x18\x01 \x01(\x0e2\x1a.ciwi.native.v1.StatusCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"w\n" +
	"\n" +
	"ServerInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vapi_version\x18\x02 \x01(\rR\n" +
	"apiVersion\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1a\n" +
	"\bhostname\x18\x04 \x01(\tR\bhostname\"\xe5\x01\n" +
	"\x0fPipelineSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vpipeline_id\x18\x02 \x01(\tR\n" +
	"pipelineId\x12\x18\n" +
	"\atrigger\x18\x03 \x01(\tR\atrigger\x12\x1d\n" +
	"\n" +
	"depends_on\x18\x04 \x03(\tR\tdependsOn\x12\x1f\n" +
	"\vsource_repo\x18\x05 \x01(\tR\n" +
	"sourceRepo\x12\x1d\n" +
	"\n" +
	"source_ref\x18\x06 \x01(\tR\tsourceRef\x12(\n" +
	"\x10supports_dry_run\x18\a \x01(\bR\x0esupportsDryRun\"\xb2\x01\n" +
	"\x14PipelineChainSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tpipelines\x18\x03 \x03(\tR\tpipelines\x12(\n" +
	"\x10supports_dry_run\x18\x04 \x01(\bR\x0esupportsDryRun\x12.\n" +
	"\x13version_pipeline_id\x18\x05 \x01(\x03R\x11versionPipelineId\"\xa8\x03\n" +
	"\x0eProjectSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vsource_kind\x18\x03 \x01(\tR\n" +
	"sourceKind\x12\x1f\n" +
	"\vconfig_path\x18\x04 \x01(\tR\n" +
	"configPath\x12\x19\n" +
	"\brepo_url\x18\x05 \x01(\tR\arepoUrl\x12\x19\n" +
	"\brepo_ref\x18\x06 \x01(\tR\arepoRef\x12\x1f\n" +
	"\vconfig_file\x18\a \x01(\tR\n" +
	"configFile\x12#\n" +
	"\rloaded_commit\x18\b \x01(\tR\floadedCommit\x12&\n" +
	"\x0fupdated_unix_ms\x18\t \x01(\x03R\rupdatedUnixMs\x12=\n" +
	"\tpipelines\x18\n" +
	" \x03(\v2\x1f.ciwi.native.v1.PipelineSummaryR\tpipelines\x12M\n" +
	"\x0fpipeline_chains\x18\v \x03(\v2$.ciwi.native.v1.PipelineChainSummaryR\x0epipelineChains\"I\n" +
	"\vProjectList\x12:\n" +
	"\bprojects\x18\x01 \x03(\v2\x1e.ciwi.native.v1.ProjectSummaryR\bprojects\"\xa7\x02\n" +
	"\rFrontPageView\x122\n" +
	"\x06server\x18\x01 \x01(\v2\x1a.ciwi.native.v1.ServerInfoR\x06server\x12:\n" +
	"\bprojects\x18\x02 \x03(\v2\x1e.ciwi.native.v1.ProjectSummaryR\bprojects\x12Q\n" +
	"\x11queued_executions\x18\x03 \x03(\v2$.ciwi.native.v1.ExecutionCardSummaryR\x10queuedExecutions\x12S\n" +
	"\x12history_executions\x18\x04 \x03(\v2$.ciwi.native.v1.ExecutionCardSummaryR\x11historyExecutions\"\x94\x01\n" +
	"\x12ProjectDetailsView\x128\n" +
	"\aproject\x18\x01 \x01(\v2\x1e.ciwi.native.v1.ProjectSummaryR\aproject\x12D\n" +
	"\tpipelines\x18\x02 \x03(\v2&.ciwi.native.v1.ProjectPipelineDetailsR\tpipelines\"\xa6\x02\n" +
	"\x16ProjectPipelineDetails\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vpipeline_id\x18\x02 \x01(\tR\n" +
	"pipelineId\x12\x18\n" +
	"\atrigger\x18\x03 \x01(\tR\atrigger\x12\x1d\n" +
	"\n" +
	"depends_on\x18\x04 \x03(\tR\tdependsOn\x12\"\n" +
	"\fdependencies\x18\x05 \x01(\tR\fdependencies\x12\x1d\n" +
	"\n" +
	"jobs_count\x18\x06 \x01(\rR\tjobsCount\x12(\n" +
	"\x10supports_dry_run\x18\a \x01(\bR\x0esupportsDryRun\x125\n" +
	"\x04jobs\x18\b \x03(\v2!.ciwi.native.v1.ProjectJobDetailsR\x04jobs\"\xc6\x02\n" +
	"\x11ProjectJobDetails\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05needs\x18\x02 \x03(\tR\x05needs\x12\x1f\n" +
	"\vneeds_label\x18\x03 \x01(\tR\n" +
	"needsLabel\x12\"\n" +
	"\rruns_on_label\x18\x04 \x01(\tR\vrunsOnLabel\x12\x1f\n" +
	"\vtools_label\x18\x05 \x01(\tR\n" +
	"toolsLabel\x12'\n" +
	"\x0ftimeout_seconds\x18\x06 \x01(\rR\x0etimeoutSeconds\x12!\n" +
	"\fmatrix_count\x18\a \x01(\rR\vmatrixCount\x12\x1f\n" +
	"\vsteps_count\x18\b \x01(\rR\n" +
	"stepsCount\x128\n" +
	"\x05steps\x18\t \x03(\v2\".ciwi.native.v1.ProjectStepDetailsR\x05steps\"\xcc\x01\n" +
	"\x12ProjectStepDetails\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12\x1a\n" +
	"\bposition\x18\x02 \x01(\rR\bposition\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x18\n" +
	"\acommand\x18\x05 \x01(\tR\acommand\x12 \n" +
	"\fskip_dry_run\x18\x06 \x01(\bR\n" +
	"skipDryRun\x12 \n" +
	"\venvironment\x18\a \x03(\tR\venvironment\"9\n" +
	"\x18GetProjectDetailsRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\x03R\tprojectId\"@\n" +
	"\x14GetJobDetailsRequest\x12(\n" +
	"\x10job_execution_id\x18\x01 \x01(\tR\x0ejobExecutionId\"\xb4\x03\n" +
	"\x0eJobDetailsView\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontext\x18\x03 \x01(\tR\acontext\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12!\n" +
	"\fstatus_label\x18\x05 \x01(\tR\vstatusLabel\x12!\n" +
	"\fcurrent_step\x18\x06 \x01(\tR\vcurrentStep\x12\x14\n" +
	"\x05agent\x18\a \x01(\tR\x05agent\x12\x12\n" +
	"\x04mode\x18\b \x01(\tR\x04mode\x12\x18\n" +
	"\acreated\x18\t \x01(\tR\acreated\x12\x18\n" +
	"\astarted\x18\n" +
	" \x01(\tR\astarted\x12\x1a\n" +
	"\bfinished\x18\v \x01(\tR\bfinished\x12\x1a\n" +
	"\bduration\x18\f \x01(\tR\bduration\x12\x1b\n" +
	"\texit_code\x18\r \x01(\tR\bexitCode\x12\x14\n" +
	"\x05error\x18\x0e \x01(\tR\x05error\x12;\n" +
	"\btimeline\x18\x0f \x03(\v2\x1f.ciwi.native.v1.JobTimelineItemR\btimeline\"\xf7\x01\n" +
	"\x0fJobTimelineItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12!\n" +
	"\fstatus_label\x18\x06 \x01(\tR\vstatusLabel\x12\x1a\n" +
	"\bduration\x18\a \x01(\tR\bduration\x12\x1b\n" +
	"\texit_code\x18\b \x01(\tR\bexitCode\x12\x14\n" +
	"\x05error\x18\t \x01(\tR\x05error\"\xa2\x01\n" +
	"\x10ExecutionSummary\x12\x1d\n" +
	"\n" +
	"total_jobs\x18\x01 \x01(\rR\ttotalJobs\x12\x1c\n" +
	"\tsucceeded\x18\x02 \x01(\rR\tsucceeded\x12\x16\n" +
	"\x06failed\x18\x03 \x01(\rR\x06failed\x12\x1f\n" +
	"\vin_progress\x18\x04 \x01(\rR\n" +
	"inProgress\x12\x18\n" +
	"\awaiting\x18\x05 \x01(\rR\awaiting\"\xba\x01\n" +
	"\x14ExecutionCardSummary\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12*\n" +
	"\x11job_execution_ids\x18\x04 \x03(\tR\x0fjobExecutionIds\x12:\n" +
	"\asummary\x18\x05 \x01(\v2 .ciwi.native.v1.ExecutionSummaryR\asummary\"\x92\x02\n" +
	"\x14RunPipelineSelection\x12&\n" +
	"\x0fpipeline_job_id\x18\x01 \x01(\tR\rpipelineJobId\x12\x1f\n" +
	"\vmatrix_name\x18\x02 \x01(\tR\n" +
	"matrixName\x12&\n" +
	"\fmatrix_index\x18\x03 \x01(\x05H\x00R\vmatrixIndex\x88\x01\x01\x12\x17\n" +
	"\adry_run\x18\x04 \x01(\bR\x06dryRun\x12\x1d\n" +
	"\n" +
	"source_ref\x18\x05 \x01(\tR\tsourceRef\x12\x19\n" +
	"\bagent_id\x18\x06 \x01(\tR\aagentId\x12%\n" +
	"\x0eexecution_mode\x18\a \x01(\tR\rexecutionModeB\x0f\n" +
	"\r_matrix_index\"~\n" +
	"\x12RunPipelineRequest\x12$\n" +
	"\x0epipeline_db_id\x18\x01 \x01(\x03R\fpipelineDbId\x12B\n" +
	"\tselection\x18\x02 \x01(\v2$.ciwi.native.v1.RunPipelineSelectionR\tselection\"\x9f\x01\n" +
	"\x11RunPipelineResult\x12!\n" +
	"\fproject_name\x18\x01 \x01(\tR\vprojectName\x12\x1f\n" +
	"\vpipeline_id\x18\x02 \x01(\tR\n" +
	"pipelineId\x12\x1a\n" +
	"\benqueued\x18\x03 \x01(\rR\benqueued\x12*\n" +
	"\x11job_execution_ids\x18\x04 \x03(\tR\x0fjobExecutionIds\"\x15\n" +
	"\x13WatchChangesRequest\"\xdf\x01\n" +
	"\vChangeEvent\x12,\n" +
	"\x12server_instance_id\x18\x01 \x01(\tR\x10serverInstanceId\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x04R\brevision\x123\n" +
	"\x06topics\x18\x03 \x03(\x0e2\x1b.ciwi.native.v1.ChangeTopicR\x06topics\x12(\n" +
	"\x10occurred_unix_ms\x18\x04 \x01(\x03R\x0eoccurredUnixMs\x12'\n" +
	"\x0fresync_required\x18\x05 \x01(\bR\x0eresyncRequired\"\xdb\x04\n" +
	"\aRequest\x12;\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1f.ciwi.native.v1.RequestMetadataR\bmetadata\x12?\n" +
	"\x0fget_server_info\x18\n" +
	" \x01(\v2\x15.ciwi.native.v1.EmptyH\x00R\rgetServerInfo\x12<\n" +
	"\rlist_projects\x18\v \x01(\v2\x15.ciwi.native.v1.EmptyH\x00R\flistProjects\x12F\n" +
	"\x13get_front_page_view\x18\f \x01(\v2\x15.ciwi.native.v1.EmptyH\x00R\x10getFrontPageView\x12G\n" +
	"\frun_pipeline\x18\r \x01(\v2\".ciwi.native.v1.RunPipelineRequestH\x00R\vrunPipeline\x12J\n" +
	"\rwatch_changes\x18\x0e \x01(\v2#.ciwi.native.v1.WatchChangesRequestH\x00R\fwatchChanges\x12Z\n" +
	"\x13get_project_details\x18\x0f \x01(\v2(.ciwi.native.v1.GetProjectDetailsRequestH\x00R\x11getProjectDetails\x12N\n" +
	"\x0fget_job_details\x18\x10 \x01(\v2$.ciwi.native.v1.GetJobDetailsRequestH\x00R\rgetJobDetailsB\v\n" +
	"\toperation\"\xc3\x04\n" +
	"\bResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12=\n" +
	"\vserver_info\x18\n" +
	" \x01(\v2\x1a.ciwi.native.v1.ServerInfoH\x00R\n" +
	"serverInfo\x12@\n" +
	"\fproject_list\x18\v \x01(\v2\x1b.ciwi.native.v1.ProjectListH\x00R\vprojectList\x12G\n" +
	"\x0ffront_page_view\x18\f \x01(\v2\x1d.ciwi.native.v1.FrontPageViewH\x00R\rfrontPageView\x12F\n" +
	"\frun_pipeline\x18\r \x01(\v2!.ciwi.native.v1.RunPipelineResultH\x00R\vrunPipeline\x125\n" +
	"\x06change\x18\x0e \x01(\v2\x1b.ciwi.native.v1.ChangeEventH\x00R\x06change\x123\n" +
	"\x05error\x18\x0f \x01(\v2\x1b.ciwi.native.v1.ErrorStatusH\x00R\x05error\x12M\n" +
	"\x0fproject_details\x18\x10 \x01(\v2\".ciwi.native.v1.ProjectDetailsViewH\x00R\x0eprojectDetails\x12A\n" +
	"\vjob_details\x18\x11 \x01(\v2\x1e.ciwi.native.v1.JobDetailsViewH\x00R\n" +
	"jobDetailsB\b\n" +
	"\x06result\"{\n" +
	"\rClientMessage\x12-\n" +
	"\x05hello\x18\x01 \x01(\v2\x15.ciwi.native.v1.HelloH\x00R\x05hello\x123\n" +
	"\arequest\x18\x02 \x01(\v2\x17.ciwi.native.v1.RequestH\x00R\arequestB\x06\n" +
	"\x04body\"\x84\x01\n" +
	"\rServerMessage\x123\n" +
	"\awelcome\x18\x01 \x01(\v2\x17.ciwi.native.v1.WelcomeH\x00R\awelcome\x126\n" +
	"\bresponse\x18\x02 \x01(\v2\x18.ciwi.native.v1.ResponseH\x00R\bresponseB\x06\n" +
	"\x04body*\xf9\x01\n" +
	"\n" +
	"StatusCode\x12\x1b\n" +
	"\x17STATUS_CODE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cSTATUS_CODE_INVALID_ARGUMENT\x10\x01\x12\x19\n" +
	"\x15STATUS_CODE_NOT_FOUND\x10\x02\x12\x18\n" +
	"\x14STATUS_CODE_CONFLICT\x10\x03\x12#\n" +
	"\x1fSTATUS_CODE_FAILED_PRECONDITION\x10\x04\x12\x1b\n" +
	"\x17STATUS_CODE_UNAVAILABLE\x10\x05\x12\x1b\n" +
	"\x17STATUS_CODE_UNSUPPORTED\x10\x06\x12\x18\n" +
	"\x14STATUS_CODE_INTERNAL\x10\a*\xdc\x01\n" +
	"\vChangeTopic\x12\x1c\n" +
	"\x18CHANGE_TOPIC_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13CHANGE_TOPIC_SERVER\x10\x01\x12\x19\n" +
	"\x15CHANGE_TOPIC_PROJECTS\x10\x02\x12\x17\n" +
	"\x13CHANGE_TOPIC_AGENTS\x10\x03\x12\x16\n" +
	"\x12CHANGE_TOPIC_QUEUE\x10\x04\x12\x18\n" +
	"\x14CHANGE_TOPIC_HISTORY\x10\x05\x12\x18\n" +
	"\x14CHANGE_TOPIC_UPDATES\x10\x06\x12\x16\n" +
	"\x12CHANGE_TOPIC_VAULT\x10\aB+Z)github.com/izzyreal/ciwi/pkg/cnp/v1;cnpv1b\x06proto3"

var (
	file_ciwi_native_v1_ciwi_proto_rawDescOnce sync.Once
	file_ciwi_native_v1_ciwi_proto_rawDescData []byte
)

func file_ciwi_native_v1_ciwi_proto_rawDescGZIP() []byte {
	file_ciwi_native_v1_ciwi_proto_rawDescOnce.Do(func() {
		file_ciwi_native_v1_ciwi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ciwi_native_v1_ciwi_proto_rawDesc), len(file_ciwi_native_v1_ciwi_proto_rawDesc)))
	})
	return file_ciwi_native_v1_ciwi_proto_rawDescData
}

var file_ciwi_native_v1_ciwi_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_ciwi_native_v1_ciwi_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_ciwi_native_v1_ciwi_proto_goTypes = []any{
	(StatusCode)(0),                  // 0: ciwi.native.v1.StatusCode
	(ChangeTopic)(0),                 // 1: ciwi.native.v1.ChangeTopic
	(*Empty)(nil),                    // 2: ciwi.native.v1.Empty
	(*Hello)(nil),                    // 3: ciwi.native.v1.Hello
	(*Welcome)(nil),                  // 4: ciwi.native.v1.Welcome
	(*RequestMetadata)(nil),          // 5: ciwi.native.v1.RequestMetadata
	(*ErrorStatus)(nil),              // 6: ciwi.native.v1.ErrorStatus
	(*ServerInfo)(nil),               // 7: ciwi.native.v1.ServerInfo
	(*PipelineSummary)(nil),          // 8: ciwi.native.v1.PipelineSummary
	(*PipelineChainSummary)(nil),     // 9: ciwi.native.v1.PipelineChainSummary
	(*ProjectSummary)(nil),           // 10: ciwi.native.v1.ProjectSummary
	(*ProjectList)(nil),              // 11: ciwi.native.v1.ProjectList
	(*FrontPageView)(nil),            // 12: ciwi.native.v1.FrontPageView
	(*ProjectDetailsView)(nil),       // 13: ciwi.native.v1.ProjectDetailsView
	(*ProjectPipelineDetails)(nil),   // 14: ciwi.native.v1.ProjectPipelineDetails
	(*ProjectJobDetails)(nil),        // 15: ciwi.native.v1.ProjectJobDetails
	(*ProjectStepDetails)(nil),       // 16: ciwi.native.v1.ProjectStepDetails
	(*GetProjectDetailsRequest)(nil), // 17: ciwi.native.v1.GetProjectDetailsRequest
	(*GetJobDetailsRequest)(nil),     // 18: ciwi.native.v1.GetJobDetailsRequest
	(*JobDetailsView)(nil),           // 19: ciwi.native.v1.JobDetailsView
	(*JobTimelineItem)(nil),          // 20: ciwi.native.v1.JobTimelineItem
	(*ExecutionSummary)(nil),         // 21: ciwi.native.v1.ExecutionSummary
	(*ExecutionCardSummary)(nil),     // 22: ciwi.native.v1.ExecutionCardSummary
	(*RunPipelineSelection)(nil),     // 23: ciwi.native.v1.RunPipelineSelection
	(*RunPipelineRequest)(nil),       // 24: ciwi.native.v1.RunPipelineRequest
	(*RunPipelineResult)(nil),        // 25: ciwi.native.v1.RunPipelineResult
	(*WatchChangesRequest)(nil),      // 26: ciwi.native.v1.WatchChangesRequest
	(*ChangeEvent)(nil),              // 27: ciwi.native.v1.ChangeEvent
	(*Request)(nil),                  // 28: ciwi.native.v1.Request
	(*Response)(nil),                 // 29: ciwi.native.v1.Response
	(*ClientMessage)(nil),            // 30: ciwi.native.v1.ClientMessage
	(*ServerMessage)(nil),            // 31: ciwi.native.v1.ServerMessage
}
var file_ciwi_native_v1_ciwi_proto_depIdxs = []int32{
	0,  // 0: ciwi.native.v1.ErrorStatus.code:type_name -> ciwi.native.v1.StatusCode
	8,  // 1: ciwi.native.v1.ProjectSummary.pipelines:type_name -> ciwi.native.v1.PipelineSummary
	9,  // 2: ciwi.native.v1.ProjectSummary.pipeline_chains:type_name -> ciwi.native.v1.PipelineChainSummary
	10, // 3: ciwi.native.v1.ProjectList.projects:type_name -> ciwi.native.v1.ProjectSummary
	7,  // 4: ciwi.native.v1.FrontPageView.server:type_name -> ciwi.native.v1.ServerInfo
	10, // 5: ciwi.native.v1.FrontPageView.projects:type_name -> ciwi.native.v1.ProjectSummary
	22, // 6: ciwi.native.v1.FrontPageView.queued_executions:type_name -> ciwi.native.v1.ExecutionCardSummary
	22, // 7: ciwi.native.v1.FrontPageView.history_executions:type_name -> ciwi.native.v1.ExecutionCardSummary
	10, // 8: ciwi.native.v1.ProjectDetailsView.project:type_name -> ciwi.native.v1.ProjectSummary
	14, // 9: ciwi.native.v1.ProjectDetailsView.pipelines:type_name -> ciwi.native.v1.ProjectPipelineDetails
	15, // 10: ciwi.native.v1.ProjectPipelineDetails.jobs:type_name -> ciwi.native.v1.ProjectJobDetails
	16, // 11: ciwi.native.v1.ProjectJobDetails.steps:type_name -> ciwi.native.v1.ProjectStepDetails
	20, // 12: ciwi.native.v1.JobDetailsView.timeline:type_name -> ciwi.native.v1.JobTimelineItem
	21, // 13: ciwi.native.v1.ExecutionCardSummary.summary:type_name -> ciwi.native.v1.ExecutionSummary
	23, // 14: ciwi.native.v1.RunPipelineRequest.selection:type_name -> ciwi.native.v1.RunPipelineSelection
	1,  // 15: ciwi.native.v1.ChangeEvent.topics:type_name -> ciwi.native.v1.ChangeTopic
	5,  // 16: ciwi.native.v1.Request.metadata:type_name -> ciwi.native.v1.RequestMetadata
	2,  // 17: ciwi.native.v1.Request.get_server_info:type_name -> ciwi.native.v1.Empty
	2,  // 18: ciwi.native.v1.Request.list_projects:type_name -> ciwi.native.v1.Empty
	2,  // 19: ciwi.native.v1.Request.get_front_page_view:type_name -> ciwi.native.v1.Empty
	24, // 20: ciwi.native.v1.Request.run_pipeline:type_name -> ciwi.native.v1.RunPipelineRequest
	26, // 21: ciwi.native.v1.Request.watch_changes:type_name -> ciwi.native.v1.WatchChangesRequest
	17, // 22: ciwi.native.v1.Request.get_project_details:type_name -> ciwi.native.v1.GetProjectDetailsRequest
	18, // 23: ciwi.native.v1.Request.get_job_details:type_name -> ciwi.native.v1.GetJobDetailsRequest
	7,  // 24: ciwi.native.v1.Response.server_info:type_name -> ciwi.native.v1.ServerInfo
	11, // 25: ciwi.native.v1.Response.project_list:type_name -> ciwi.native.v1.ProjectList
	12, // 26: ciwi.native.v1.Response.front_page_view:type_name -> ciwi.native.v1.FrontPageView
	25, // 27: ciwi.native.v1.Response.run_pipeline:type_name -> ciwi.native.v1.RunPipelineResult
	27, // 28: ciwi.native.v1.Response.change:type_name -> ciwi.native.v1.ChangeEvent
	6,  // 29: ciwi.native.v1.Response.error:type_name -> ciwi.native.v1.ErrorStatus
	13, // 30: ciwi.native.v1.Response.project_details:type_name -> ciwi.native.v1.ProjectDetailsView
	19, // 31: ciwi.native.v1.Response.job_details:type_name -> ciwi.native.v1.JobDetailsView
	3,  // 32: ciwi.native.v1.ClientMessage.hello:type_name -> ciwi.native.v1.Hello
	28, // 33: ciwi.native.v1.ClientMessage.request:type_name -> ciwi.native.v1.Request
	4,  // 34: ciwi.native.v1.ServerMessage.welcome:type_name -> ciwi.native.v1.Welcome
	29, // 35: ciwi.native.v1.ServerMessage.response:type_name -> ciwi.native.v1.Response
	36, // [36:36] is the sub-list for method output_type
	36, // [36:36] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_ciwi_native_v1_ciwi_proto_init() }
func file_ciwi_native_v1_ciwi_proto_init() {
	if File_ciwi_native_v1_ciwi_proto != nil {
		return
	}
	file_ciwi_native_v1_ciwi_proto_msgTypes[21].OneofWrappers = []any{}
	file_ciwi_native_v1_ciwi_proto_msgTypes[26].OneofWrappers = []any{
		(*Request_GetServerInfo)(nil),
		(*Request_ListProjects)(nil),
		(*Request_GetFrontPageView)(nil),
		(*Request_RunPipeline)(nil),
		(*Request_WatchChanges)(nil),
		(*Request_GetProjectDetails)(nil),
		(*Request_GetJobDetails)(nil),
	}
	file_ciwi_native_v1_ciwi_proto_msgTypes[27].OneofWrappers = []any{
		(*Response_ServerInfo)(nil),
		(*Response_ProjectList)(nil),
		(*Response_FrontPageView)(nil),
		(*Response_RunPipeline)(nil),
		(*Response_Change)(nil),
		(*Response_Error)(nil),
		(*Response_ProjectDetails)(nil),
		(*Response_JobDetails)(nil),
	}
	file_ciwi_native_v1_ciwi_proto_msgTypes[28].OneofWrappers = []any{
		(*ClientMessage_Hello)(nil),
		(*ClientMessage_Request)(nil),
	}
	file_ciwi_native_v1_ciwi_proto_msgTypes[29].OneofWrappers = []any{
		(*ServerMessage_Welcome)(nil),
		(*ServerMessage_Response)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ciwi_native_v1_ciwi_proto_rawDesc), len(file_ciwi_native_v1_ciwi_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ciwi_native_v1_ciwi_proto_goTypes,
		DependencyIndexes: file_ciwi_native_v1_ciwi_proto_depIdxs,
		EnumInfos:         file_ciwi_native_v1_ciwi_proto_enumTypes,
		MessageInfos:      file_ciwi_native_v1_ciwi_proto_msgTypes,
	}.Build()
	File_ciwi_native_v1_ciwi_proto = out.File
	file_ciwi_native_v1_ciwi_proto_goTypes = nil
	file_ciwi_native_v1_ciwi_proto_depIdxs = nil
}
